### ISSUE TITLE
Create Conflict resolution process

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#103]
How does conflict get resolved at Enspiral?

Sometimes it might be because of a breach of our Code of Conduct (#102). Or it could just be two people who don't get along anymore
- [x] Find volunteers to progress this work
- [ ] Gather resources (Loomio, EDA, Buurtzorg, Reinventing Organisations wiki, etc)
- [ ] Draft first version
- [ ] Start Loomio discussion and propose that we adopt this conflict resolution process
- [ ] Update handbook with new process

**Comment by alannallama** [comment]
Comment from Billy Matheson....

I quite like a process where:

1. Anyone can initiate mediation in the network - either one of the parties involved (or a third party/bystander). 
2. They just have to find someone who they trust to set up the formal mediation (like a personal steward). 
3. That person then contacts the other party and extends the invitation to formal mediation.
4. If the other party is up for it, they nominate their own mediator (personal steward) who they trust and ask that person to mediate on their behalf.
5. The two nominated mediators (who have consented to their roles and agreed to work together) then get together to work out a process that they both think will add value (I think they need to commit to at least 3 sessions and a retrospective) and they then invite their ‘clients’ to join them in that process.
6. The three sessions then take place. These are co-facilitated by the two mediators. More sessions can happen if all parties agree it’s useful.
7. The two mediators then meet to do the retrospective of the mediation process. They can invite the two parties to “fishbowl” or observe that conversation if they agree that would be useful.
8. The two mediators then work together to create a summary document that they both agree to share with both parties.
9. I think this process should be free of any findings or agreements. 
10. The two parties are invited to make any commitments they want to each other based on the process.

**Comment by rdbartlett** [comment]
@camia-young has volunteered to join in with me and @lucasexpresso to progress this work. I've updated the issue with a to-do list for what I think the process should be. 

I've also added the Sprint 9 milestone because ideally we'll get it finished in the next couple of weeks so it is not holding up the stewardship upgrade work.

**Comment by rdbartlett** [comment]
The [Loomio conflict resolution process](https://github.com/loomio/loomio-coop-handbook/blob/master/conflict_resolution.md) seems like a reasonable place to start. We'd have to adapt it a bit though. 

For this I'm assuming that many but not all contributors will have stewards. So I'm expecting the stewards will play a key role, but there needs to be some backstop for people who don't have one.

**Comment by Camia-Young** [comment]
@rdbartlett thank you for on boarding me. 

What is the outcome we hope to achieve to reach a resolution on this?

**Comment by rdbartlett** [comment]
Whoops I made a mess of things by working in Waffle and Github at the same time 💩 

I've added a todo list to the issue again. 

The outcome I'm hoping for is a Loomio decision to accept the first version of a network-wide conflict resolution process.

I'm wondering if it should be a Standard decision or a Significant Decision? http://handbook.enspiral.com/decisions_agreement.html

**Comment by rdbartlett** [comment]
Personally I think it should be a significant decision, because we want people to commit to the process when they join as contributors.

**Comment by Camia-Young** [comment]
I need a bit to time to digest what you already know.  Ill read/think through the texts you have sent. Then where do we create a working draft we can all work in together simultaneously and comment on, like a google doc? Does that exist in Github?

**Comment by rdbartlett** [comment]
For realtime quickfire collaborative document writing, Google Docs is probably the simplest. We can do it in Github but it is a much more structured process, more suited to making a formal proposal to change a text, rather than hacking on a doc together.

**Comment by Camia-Young** [comment]
In your experience how often does conflict occur at Enspiral that would require conflict resolution? And can we get a sense of what kind of conflict we might be talking about? conflict is pretty wide open.  Where I work it is about noise, space, respect for one another's belongings, leaving the damn lights on after leaving!!!! but my guess is it is different then that with Enspiralites? 

Im of the mind that there are different depths to conflict, so there may be a spectrum of options depending on the conflict:
LOW LEVEL:  suggested inter-enspiral protocol to guide people to talk things through with one another if there is tension or low level discord between two people.
MID LEVEL: the conflict is upsetting work and wellbeing, it may involve 2 or more people.
HIGH LEVEL: there is a significant effect on one or more person's wellbeing which they have identified and asked for help to work through. 

If we have a range we can create a staged process tailored to the occurrences. Im just throwing this out there as a starting point, but Im more or less guessing around the kind of conflict you may have in the Enspiral day to day.  

Maybe a quick pole would not be a bad idea? Then we can be more specific, less generic? We could also ask folks if they have used existing methods that worked for them?

**Comment by lucasexpresso** [comment]
Rich, I'll start reading those. What does the sprint 9 milestone means?

**Comment by rdbartlett** [comment]
Hey @lucasexpresso I think you accidentally closed this issue prematurely :)

The Sprint 9 milestone just means we're hoping to have the work complete by August 5th (but there's no punishment for it running over time 😹)

**Comment by lucasexpresso** [comment]
You can see how eager I'm. :) Sorry!

**Comment by coopchange** [comment]
Ah, serendipity that I just ran into the old loomio thread on Conflict Resolution- I just added some nifty conflict resolution preemptive worksheets. Look forward to this coming to a Loomio thread near us ;)

**Comment by rdbartlett** [comment]
Oh awesome thanks @coopchange I had forgotten about that Loomio. ([Link here for reference](https://www.loomio.org/d/3kebtDN4/code-of-conduct-and-conflict-resolution-documents).

I'm going to continue the conversation there so all the context is in one place.

**Comment by lucasexpresso** [comment]
One of the things it occurred to me it is not directly related to the process of conflict resolution, but on the prevention. On the on boarding of new people in  Buurtzorg they offer a non violent communication training. I think they also have a conflict management training. I haven’t heard back from Jos yet.

**Comment by lucasexpresso** [comment]
The other likely source of conflict I sense is people not knowing each other deeply. This happens when groups become big and people don't have a physical connection. Big groups struggle honouring the skills and dedication each member brings to the team. In Brazil where, I came from the ancient Tupi tribes would always split in two when they reached a certain size so that every one knew each other well and the group could benefit from being lean and agile.

**Comment by coopchange** [comment]
*Thought on process:* Once resources are collected, it might be nice to do something similar, but slightly more in-depth, to the Geek Feminism CoC [evaluations](http://geekfeminism.wikia.com/wiki/Code_of_conduct_evaluations#Effective_codes_of_conduct); I was thinking to create a table to compare/contrast the various outlines of the CoC's & conflict resolution documents (for [example](https://docs.google.com/spreadsheets/d/1eD_-xsFgIWLO4YjdCjy7uQj7bbGolkwSmlDxv3iTRxg/edit?usp=sharing))... however,
*Question on process:* From the Loomio, it seems like there is two ideas on the table ATM- either creating a CoC + Conflict Resolution doc, or creating CoC + CResolution + Abuse & Harm Procedures... does anyone have a strong impression of which of these is the preferable way forward?

Or are we purely focusing on getting the Conflict Resolution document to a reasonable level & reiterating community feedback process for the CoC as is? I feel like the other noteable design question that was brought up by several was the need for (at least qualitatively) different processes (and reflective copy) for minor, moderate, & major incidents

Also, the one thing that I especially thought was positive from the Embassy Network document was the Preventative Actions section; something to maybe keep in mind especially as the Stewardship Upgrade looks to be a significant practice of this nature.

**Comment by joshuavial** [comment]
@Camia-Young @lucasexpresso @rdbartlett - any updates on what the plans are for this ticket?

**Comment by Camia-Young** [comment]
We hosted a zoom meeting with 6 people to discuss how to approach the guidelines. It was more of a getting to know one another and familiarizing ourselves with the material collected to date. We are scheduling another meeting to nut out a plan and raise a bucket for the work to be done.

**Comment by coopchange** [comment]
Bucket drafting is in motion, see the gDoc linked in context of the "Code of Conduct... Next Steps" Loomio-[thread](https://www.loomio.org/d/YWb07Fta/code-of-conduct-conflict-resolution-and-mediation-next-steps)

**Comment by joshuavial** [comment]
This is "done enough" and will be replaced by the code of conduct tickets
