### ISSUE TITLE
catalyst monthly checklist

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#104]
create a new section in the handbook for catalyst workflows and start a monthly checklist
- [x] check contributor opt in feedback
- [x] ping bucket holders for updates

**Comment by susanbasterfield** [comment]
https://docs.google.com/spreadsheets/d/15cK9rf6Pmh4QnTM-HMoXHRVuzryqyl_uNCw-j99dAYQ/edit#gid=416426898

**Comment by joshuavial** [comment]
Just a note that I've restricted view access to that doc to catalysts because it had people's names associated with the feedback and I don't think we had explicit consent for that.

**Comment by susanbasterfield** [comment]
Thank you

**Comment by susanbasterfield** [comment]
Sent loomio ping on 25th as reminder for update.  

Bucket Updates for:

Enspiral Google App Security
Prototype Real Time Contributions
Financial Hardship Subsidies
Counselling Bucket
Kamp Kaitaki hui #2
Fairy Blog Mother
Sponsor Mikey to CampJS in Australia

No Updates 15 Buckets.
Tagged each with a request

**Comment by susanbasterfield** [comment]
Emailed reminders for cobudget

**Comment by susanbasterfield** [comment]
Posted link for opt in/out comments into slack

**Comment by susanbasterfield** [comment]
Feel great about the bucket updates - 17 out of 25 this month, feels like traction and big improvement

**Comment by susanbasterfield** [comment]
opt in comments posted in slack for review.  Bucket updates chased.
