### ISSUE TITLE
Google Apps security at Enspiral

### ISSUE THREAD

**Issue by mdshearer** [enspiral/improvements#105]
Our google apps security is sadly lacking (after a recent google security workshop, Google gave us a rating of 24/100). We've had a number of recent serious phishing attacks. (Serious in that it wasn't "send your money to Nigeria", it was more like Director says to accountant do something with our money, with correct email headers and signature.

We (Operations) are keen to do some serious work on this but need some funding.

Here's our cobudget request: http://beta.cobudget.co/#/buckets/476

**Comment by mdshearer** [comment]
Bucket funded yesterday.

* We have removed Apps accounts for most people who have requested offboarding and have audited the rest. 
* We've setup a new spreadsheet for tracking who has access.
* We're trialling different admin accounts to make sure the highest risk one's are separated from "normal" accounts.
* I'll be joining a followup Google security hangout next week to learn more about security vulnerabilities.
* If we boost our security score enough by the end of the month (that will be easy!!) Google will send us security keys for our super-admin accounts.

**Comment by joshuavial** [comment]
Any update @mdshearer ?

**Comment by mdshearer** [comment]
Updated bucket at end of month but didn't think to look here.
-All admin roles secure
-We didn't boost our security score by enough so still working on this. Will raise separate bucket to buy security keys for super admins.
-Working on comms to all enspiral account holders with recommendations for the easiest ways to improve their security.
-May run a simulated attack if we have funds left. Though it's taken longer than expected to audit admin accounts.

**Comment by mdshearer** [comment]
This project is finally done.
- Instead of communicating to everyone about security Rob G is going to post a blog.
- All super-admins are now or will soon be using security keys to access their separate accounts.
- No funding for simulated attack at the moment but will look in to that after the blog posts.
- Google apps security notifications are now zapped straight in to Slack: Ops. This will allow us to quickly suspend an account and contact the user if there is any suspicious activity.
