### ISSUE TITLE
Buckets staying in "funding" for ages

### ISSUE THREAD

**Issue by alannallama** [enspiral/improvements#106]
Because Cobudget has no deadline function, buckets that go forward for funding just stay there indefinitely. Sometimes, the person who raised it is completely disengaged (after months have gone by). Funds are tied up in the bucket, which stays partially funded, but it's not clear if the bucket proposer is even committed to doing the work if it gets fully funded, or if the bucket will ever be fully funded. 

Possible solutions, in descending order of ideal-ness and ascending order of apparent achievability...

1. Cobudget implements a funding deadline feature. This has been designed and scoped previously in their backlog (eg, options to determine if a bucket isn't fully funded at the deadline, if it goes through with current funding or is cancelled - 'scale to fit' vs 'zero or hero')
2. Enspiral implements a policy that all bucket raisers have to manually specify an end date for funding, and whether it's  'scale to fit' vs 'zero or hero' (ie, what happens when the date is reached if not fully funded).
3. We apply the '90 day' limit or a similar basic time frame to all buckets - Catalysts cancel all buckets that have not been fully funded after 90 days in "funding" (perhaps giving bucket sponsors a chance to extend this if they proactively respond to comments on their bucket indicating they are still committed and want funding to continue - this would cover long term savings buckets with committed sponsors).

Ideally, with Catalysts engaging with every bucket before it goes through to funding, it would be possible to make sure option 2 is fulfilled above for each one. But the Catalysts already have limited capacity so 3. might be more realistic.

**Comment by joshuavial** [comment]
I think number 2 is the best bet, easy to do by hitting up current bucket holders and asking them to edit the bucket with a deadline in it. Archiving buckets is now a thing so refunding people is no problem.

**Comment by mdshearer** [comment]
I agree that number 2 is easiest. 
Number 1 would be ideal and seems like a feature that would benefit many groups in the future.

**Comment by simontegg** [comment]
Noting that getting a new policy passed [seems harder](https://www.loomio.org/d/ajX4pDTU/how-should-bucket-reporting-work-) than you might expect. 

Another approach would be to approach bucket holders with inactive, partially funded buckets and find out what their needs are. Happy to do this. Please advise on me this course of action (privately if necessary)?

#coachingopportunity

**Comment by mdshearer** [comment]
I think Susan was working on that but it's a bit of a mission...
Can you build us some features? :D

**Comment by simontegg** [comment]
Ha! Maybe @susanbasterfield can comment. 

PS. I think organisational coaching is ultimately more valuable than tools. Though they're cool too.
> People and interactions over tools and processes

**Comment by susanbasterfield** [comment]
@simontegg @mdshearer been doing that already - working through options and possibilities with Beka and Sarah on their open funded buckets.  nb my preference is always real conversations over tools and rules!

**Comment by mdshearer** [comment]
I certainly agree on people over process/tools/rules etc. And, when you regularly see the same problems, sometimes a tweak to a tool or rule can make a world of difference to the people that are trying to maintain things!

**Comment by simontegg** [comment]
That's great to hear.
My noticing is that what should perhaps be tweaks sometimes end up being contentious. 
My wondering is around how people are encountering tweaks, and the cumulative impact of new policies. I can understand that process tweaks and additions have worked well in many cases.

I have some thoughts in a private thread about this which I'll let work through. Then perhaps this will be another issue.

**Comment by gcassel** [comment]
I think Cobudget really needs to develop a funding deadline feature, in order to become extremely valuable for many use-cases in the wide world of organizations.   (And needs 'scale to fit' and 'zero or hero' labels.)

**Comment by mdshearer** [comment]
+5 to that!

**Comment by joshuavial** [comment]
I feel like this ticket is being addressed by #20 though I like the people and interactions over tools and processes.

**Comment by alannallama** [comment]
I agree this will be helped in the future by other processes coming online,
but I would suggest taking action to clear out the old buckets hanging out
in "funding" so we can move into a new phase.

On 30 May 2016 at 10:30, Joshua Vial <notifications@github.com> wrote:

> I feel like this ticket is being addressed by #20
> <https://github.com/enspiral/improvements/issues/20> though I like the
> people and interactions over tools and processes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/enspiral/improvements/issues/106#issuecomment-222386622>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFPn_t9VTrznp4N1VNUYAY0Fh0awklIlks5qGhN6gaJpZM4Ig1mD>
> .
>



-- 
<http://loomio.org>
*Alanna Krause*
Co-Founder & Co-op Member
