### ISSUE TITLE
Need for a network Want Ads / Incoming Opportunities Board

### ISSUE THREAD

**Issue by charleydavenport** [enspiral/improvements#107]
Enspiral Services has a Loomio Channel "Marketplace" for incoming opportunities. In Ops, we monitor and respond to the Enspiral Foundation Helpdesk, and sometimes there are incoming requests in which we don't immediately know who to forward to or who within the network might be interested. While it's not a huge volume, and it's part of our scope to be able to respond to these requests, I think it could be better and potentially bring in more interest, without creating more noise. 

As an admin, my current options are to:
- re-direct the message to particular people/groups/ventures
- post in Marketplace Loomio
- post in Slack Watercooler
- post in Slack Want-ads channel
- post here in github ? 

Ideally, with incoming messages interpreted by admin as being worthy of the networks attention, with potential interest, there could be a more central depository of these messages, and a way to bring it to the attention of more contributors who might be interested.

One idea I have is a centralised "pinboard" of sorts where I could deposit incoming messages of interest. Anyone who is signed up to the board could tag particular subjects/hashtags of topics they'd be interested in within the network. (e.g. "Youth Mentoring", "Workplace Sustainability", "Eco-products", "Connecting in Wellington", "Intra-network Opportunities"). 

All the Admin would have to do is respond to the incoming message, saying "thanks" and with encouragement about their interest in connecting and a confirmation that their interest has been shared with the network. Then we could provide the incoming contact information to the message board for any contributor to respond to. Once a contributor has picked up the interest, they could then record a note to say they've done so. ... 

In fact, could we simply create a new Github board for this? I'll leave it here for the moment. - Charley, Ops Team

**Comment by joshuavial** [comment]
I love the idea of an incoming board for requests - the only question I have is about the privacy settings on it.
