### ISSUE TITLE
Issue with offboarding contributors from Cobudget that have money in "funding" buckets

### ISSUE THREAD

**Issue by mdshearer** [enspiral/improvements#109]
If someone has money in a currently funding bucket and we remove them from Cobudget (because they've requested to offboard from Enspiral), those funds disappear from Cobudget and that funding bucket. Then, Cobudget is out of sync with the my.enspiral Collab Funding account.

Further more, the only way to identify whether someone has funds in a funding bucket is to check each funding bucket for a contribution from them. While this is a rare instance its a potential problem that could cause balance errors and lots of work for Operations.

**Comment by joshuavial** [comment]
Tricky, not sure I can think of a solution which doesn't involve a cobudget feature. @data-doge can you think of any workarounds?

**Comment by joshuavial** [comment]
Removing the improvements tag as this doesn't relate to the improvements system.
