### ISSUE TITLE
Clarify Member coming back from Hiatus

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#114]
When a member wants to come back from hiatus the process is unclear, since they are often out of the loop and don't know who to reach out to.

Should we document this in the handbook or send some kind of reminder email?

**Comment by mdshearer** [comment]
And what is the process for announcing them...? Ops will need to add them back in so would be good to know how this works.

**Comment by mdshearer** [comment]
Clarified in member loomio proposal last month

**Comment by mdshearer** [comment]
This has been completed with a member loomio proposal. https://www.loomio.org/d/XPcd9bQ6/proposal/A7pUIwsc
