### ISSUE TITLE
Rename Members to Partners

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#115]
- [x] Loomio decision agreeing to the change
- [ ] get legal advice about using the word Partner

Update all the things
- [ ] handbook
- [ ] website
- [ ] mailchimp welcome emails
- [ ] Loomio groups
- [ ] slack channel
- [ ] google groups
- [ ] ops systems

**Comment by joshuavial** [comment]
@mdshearer @alannallama anything else you can think of that would need to be updated?

**Comment by mdshearer** [comment]
Google groups. Ops systems.

**Comment by mdshearer** [comment]
Woops!

**Comment by joshuavial** [comment]
The Loomio decision has passed though there were some concerns raised from @agentlewis about whether this needed to be a significant decision or not. I added a task to #138 to update the [decision agreement](http://handbook.enspiral.com/decisions_agreement.html) to improve clarity.

It also highlighted a flaw in our significant decisions process which lead to #148 

Some of our Lawyers raised concerns about the legal interpretation of the word Partner. @SlimeyD will raise a bucket to get some legal advice before progressing further.

**Comment by SlimeyD** [comment]
Did you want to update on the cost of the legal advice so I can adjust the
bucket accordingly?
