### ISSUE TITLE
Conscious Consumers

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#121]
Ben and the Conscious Consumers board are keen for CC to join as a proto-venture
- [ ] venture stewards
- [ ] profile

**Comment by agentlewis** [comment]
will action on this over the next week.

**Comment by joshuavial** [comment]
@agentlewis any updates?

**Comment by agentlewis** [comment]
@joshuavial I got swamped. I talked to Ben last week and we planned to sit down on this next weekish.

**Comment by joshuavial** [comment]
@agentlewis any updates?

**Comment by joshuavial** [comment]
Would you like me to find someone else to pick this up @agentlewis ?

**Comment by agentlewis** [comment]
@joshuavial no its ok, ill get the ball rolling on it this week. CC have been on a big push and didn't have time for it. Thanks for asking.

**Comment by agentlewis** [comment]
Have met with Ben and wrote out an action plan for moving on this.

It will be CC becoming a proto venture.
