### ISSUE TITLE
Explore advice process

### ISSUE THREAD

**Issue by simontegg** [enspiral/improvements#122]
- [ ] simon and JV to work on decision evaluation template
- [ ] JV to research advice process
- [ ] JV to fill out for services reformat and improvements
- [ ] guidelines for types of decisions this migh be appropriate for
- [ ] draft of advice process description

**Comment by joshuavial** [comment]
As I mentioned in the loomio thread I think this should include an amendment to the decision making agreement and also an amendment to the finance agreement in how cobudgeting works.

**Comment by joshuavial** [comment]
@simontegg I think the advice process should be in our decision making agreement instead of a guideline - are you happy if I close this ticket and do the work in #138

**Comment by simontegg** [comment]
I think this is like our `concepts` and `exercises` split in the EDA curriculum. Decisions agreement might reference Advice Process but it lives somewhere else. Same for consensus process.

**Comment by joshuavial** [comment]
Will be picking this ticket up as part of sprint 5

**Comment by joshuavial** [comment]
Notes from the teal advice process

The advice process

Almost all Teal organizations use the “advice process.” It comes in many forms.

but the essence is consistent: Any person can make any decision after seeking

advice from

1) everyone who will be meaningfully affected, and

2) people with expertise in the matter. Advice received must be taken into

consideration.

The point is not to create a watered-down compromise that accommodates

everybody’s wishes. It is about accessing collective wisdom in pursuit of a sound

decision: with all the advice and perspectives the decision maker has received,

they choose what they believe to be the best course of action. Advice is simply

advice. No colleague, whatever their importance, can tell a decision-maker what

to decide. Usually, the decision-maker is the person who first noticed the issue,

or the person most affected by it. 

In practice, this process proves remarkably effective; It allows anybody to take

the initiative.

It&#39;s not consensus

It takes practice! 

 When you want to make a decision, pause and ask: Am I the best person

for this decision? (That is, the person most closely linked to the decision, or

the person with most energy, skill and experience to make it?). If not, ask

the person you think is better placed to take the initiative. If he/she doesn&#39;t

want to, you might be best placed after all.

 If you are the right person, identify those from whom you should seek

advice. Approach them and explain what you are doing. (&quot;I&#39;m playing by the

advice process. Here is an opportunity I see. This is the decision I

propose to take. Can you give me your advice?&quot;). You can also share who

else you are asking for advice. Once you&#39;ve received advice and made

your decision, inform those you consulted (and anyone else who should

know).

 When colleagues ask you to make a decision (&quot;What should I do? &quot;),

instead ask them &quot;What is your proposed decision? &quot;. State clearly that

you don’t give approval for the decision, instead, share your advice and

suggest who else to ask. Remind them the decision is theirs.

**Comment by susanbasterfield** [comment]
I'm writing a blog post about this

**Comment by simontegg** [comment]
Relevant http://sivers.org/2c

**Comment by joshuavial** [comment]
The advice process is bubbling away informally - closing this ticket and we can create a new one when it feels right to document it
