### ISSUE TITLE
Makers Org NZ

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#127]
Work with Richard Fortune for Makers Org NZ to join as a proto-venture
- [ ] stewards
- [ ] profile

**Comment by richardofortune** [comment]
Who should I speak to first and what do I need to do that we're in a good place to take this further?

**Comment by richardofortune** [comment]
Any thoughts on what I can do to get this moving? Is there a deliverable I can pull together to help this along?

**Comment by joshuavial** [comment]
@richardofortune I will ping all members and see who I can find to steward it.

**Comment by richardofortune** [comment]
Thanks!

**Comment by joshuavial** [comment]
@rdbartlett will find a member to do the rounds and see if we can find stewards
