### ISSUE TITLE
Create new Badge/Role: Agreement Awareness Squad

### ISSUE THREAD

**Issue by agentlewis** [enspiral/improvements#128]
Wondering if we can create a new group of peeps who know our agreements through and through and are well positioned to provide knowledge where needed about them.

I imagine these could start as a group of members, but like catalysts need not be limited to them.

ps i guessed a bunch of labels...

**Comment by genevievebelle** [comment]
I'm keen. I imagine a way this team might be useful would be to model behaviour by referencing the Agreements in Loomio etc when relevant so that they slowly sink in - rather than being called on it's an extra vigilance thing. Could we pay for the time of a couple of the CWG to run a workshop?

**Comment by simontegg** [comment]
I'm keen. I know the agreements back to front. 
But I'm not interested in agreements 'compliance.', or even 'agreements education'. More of a conversations about what works for people when we notice they're out of alignment.

Related:
https://flowchainsensei.wordpress.com/2014/04/20/can-we-imagine/

**Comment by agentlewis** [comment]
renamed to @genevievebelle better name :) nom nom
