### ISSUE TITLE
Integrate onboarding documentation into Enspiral Handbook

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#13]

**Comment by susanbasterfield** [comment]
Blocked pending Chloe investigating Mailchimp links

**Comment by mdshearer** [comment]
We probably need to find another way out of this one but not sure what it is. @joshuavial I'm not sure how to create a permalink...

**Comment by joshuavial** [comment]
Maybe we should remove mailchimp as the source of truth for these initial comms and store them somewhere else (directly in the handbook perhaps) - then the email can just reference that part of the handbook.

**Comment by phillcoxon** [comment]
I think referencing the handbook is a great idea. One consistent source of information, easy to find again later, no need to continually check and update mailchimp emails.

**Comment by mdshearer** [comment]
Sounds like a possibility. What does that mean in practise? 6 PDF's attached to the handbook? That would mean that any changes to the actual emails will not populate over to the handbook.

**Comment by phillcoxon** [comment]
@mdshearer - we could have the email content set up directly in the handbook such as this example:  https://github.com/enspiral/handbook/blob/onboarding-series/onboarding-email-0-welcome.md

If those pages are added to the gitbook version then we get nice HTML pages we can link to from emails.  

My original thinking was that we could use an iframe to pull the gitbook content directly into the emails but iframe support looks pretty dodgy across email clients still so not ideal.

**Comment by agentlewis** [comment]
@phillcoxon I would avoid putting an iframe in an email. that is very brittle.

could we not just have a single link and a message each week? than we could just put them in a folder in our handbook.

I like this because:
a. it gets people familiar with going to the handbook to learn
b. if they ever want to read a particular thing again they know its in the handbook - rather than searching there email for it.

**Comment by joshuavial** [comment]
We'll just duplicate this content in both mailchimp and the handbook - there doesn't seem to be an easy way to have one source of truth

**Comment by susanbasterfield** [comment]
@mdshearer now that Chloe is back in country maybe we could progress this again?

**Comment by mdshearer** [comment]
@susanbasterfield We'd need a new bucket to progress this. If someone wants to organise funding we can pick it up again.

**Comment by susanbasterfield** [comment]
@mdshearer If you send me the files I can do the work

**Comment by mdshearer** [comment]
@susanbasterfield Files...? Do you mean the static emails converted in to PDFs?

**Comment by susanbasterfield** [comment]
@mdshearer yes, if possible?

**Comment by susanbasterfield** [comment]
thanks @mdshearer all done now just waiting for pull request approval

**Comment by susanbasterfield** [comment]
uh oh accidentally closed what now?

**Comment by susanbasterfield** [comment]
Completed just need to figure out how to create the heading
