### ISSUE TITLE
venture status rabid

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#135]

**Comment by susanbasterfield** [comment]
Susan has meeting with Josh on 13th July

**Comment by susanbasterfield** [comment]
Great meeting with Josh - 2 actions pending 
1) Josh will meet with another Enspiral Member to talk through his thinking/ideas for his personal engagement
2) At the Rabid Quarterly meeting the last week of July, Josh will propose that Rabid cease formal ventureship with Enspiral.  His sense it that this will not elicit any negative reaction, but is open to reconsidering his position if it does.

**Comment by susanbasterfield** [comment]
Emailed Josh for update

**Comment by susanbasterfield** [comment]
Josh emailed back and asked for more time

**Comment by susanbasterfield** [comment]
Emailed Josh and asked for a call or in person

**Comment by susanbasterfield** [comment]
Another update - met with Josh last week and he is preparing a Loomio to announce Rabid moving to 'friend' status
