### ISSUE TITLE
Enspiral comms culture

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#137]
Our online communications with each other can sometimes be quite intimidating and alienating for people, as well as stressful and draining for the participants. 

What can we do to improve this?

**Comment by gcassel** [comment]
It can also be intimidating, alienating, stressful and draining to be able to interact only online-- while being well aware that others frequently discuss issues in person.

I think Enspiral (and everyone else!)  can greatly improve protocols and practices for synergizing live and asynchronous communications.    

I think one of the most fundamentally valuable possibilities is to start offering live tele-meetings which are each dedicated to a specific Loomio discussion or proposal.   I also think it's especially important for the people who *disagree* with each other to talk live-- and, hopefully, reduce the volume of Loomio text.
