### ISSUE TITLE
Improve decision making agreement

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#138]
- [ ] add advice process
- [ ] split out processes from agreements
- [ ] clarity about process for small modifications to agreements

**Comment by simontegg** [comment]
I think this needs more share understanding before moving forward.

**Comment by simontegg** [comment]
For reference:
http://randsinrepose.com/archives/the-process-myth/

**Comment by joshuavial** [comment]
@simontegg do you think an in person workshop would be a good next step?

**Comment by joshuavial** [comment]
Moving this ticket back a sprint

**Comment by simontegg** [comment]
Well, well, well
http://thefutureprimaeval.net/on-going-against-the-consensus/
