### ISSUE TITLE
Enspiral wide marketplace for leads

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#142]

**Comment by susanbasterfield** [comment]
@mdshearer is this the same as your help wanted loomio do you think?

**Comment by mdshearer** [comment]
I reckon yeah. Can we say this one is done...?

**Comment by susanbasterfield** [comment]
I think so!

**Comment by mdshearer** [comment]
This issue was resolved with the renaming of Ask Enspiral to: Enspiral opportunities // Ask Enspiral
https://www.loomio.org/g/9G8VrBKv/enspiral-enspiral-opportunities-ask-enspiral
