### ISSUE TITLE
Enspiral Communities

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#146]

**Comment by agentlewis** [comment]
Yay

**Comment by joshuavial** [comment]
Pushing this back to september

**Comment by joshuavial** [comment]
Initial thinking is here https://docs.google.com/document/d/18kCoGHVQ1au0vOiFlmv1Eic_Paxr1KN5bjnB9LTiBug/edit#heading=h.t0rebssowxb and this work will be incorporated into the Growth working group stream #175
