### ISSUE TITLE
Enspiral swarm on OSOS

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#147]
Help to get a whole lot of Enspiral people to participate in OSOS

**Comment by susanbasterfield** [comment]
@silviazuur anything else we catalysts can do to help?  What would be most helpful?

**Comment by silviazuur** [comment]
Thanks for checking in @susanbasterfield 

Some key things:
Active visible engagement in this loomio: https://www.loomio.org/d/oHekuYwl/launching-os-os-2016-together-
Perhaps a blog on why "Enspiral" is excited about OS//OS? 
Help us shoulder tap people to share the message: http://opensourceopensociety.com/share.html
Thinking about how "Enspiral" can leverage from the event
Helping us sell tickets!
