### ISSUE TITLE
Abstains hurt significant decisions

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#148]
I think we have a problem with our process for making significant decisions. As it is [currently stated](http://handbook.enspiral.com/decisions_agreement.html) (more than 50% of people stating a position need to agree) every abstain that is cast reduces the likelihood of the decision happening.

This contradicts the spirit of abstaining (I'm ok either way)

A good example is the [Loomio to change members to partners](https://www.loomio.org/d/pvF9UEJL/proposal/rIk124Vn). There is debate about whether it is a significant decision or not but if it is it would fail the test narrowly.

What other algorithms could we use for raising the bar for alignment on significant decisions?

**Comment by agentlewis** [comment]
I would be happy with a minimum number of votes (general). possibly from members. 

ie a serious descision requires 
a: at least 10% of enspiral foundation contributors vote
b: at least 50% of enspiral foundation members vote
c: Agreements > 5 * Disagrees
d: Agreements > Abstain

Abstain counts towards the a and b. And also safeguards that a certain number of people have to be pro change

ps the 5*disagree would need to be battle tested. It maybe it should be 3 or 4

**Comment by agentlewis** [comment]
@joshuavial ^

**Comment by joshuavial** [comment]
Feels like the right direction, I'm not a fan of % engagement thresholds though and would much prefer a minimum amount of time instead.

I think the most important thing is that this is a simple test that people can do in their head in 2 seconds. Criteria like % of certain classes of Enspiral folks would involve quite a lot of work and I would suggest cutting them from a complexity point of view.

I also think that the number of abstains should be immaterial to whether it passes or not. Any situation where more abstains make it less likely to pass feels like a bug to me.

**Comment by susanbasterfield** [comment]
I wonder what a Loomio proposal about abstentions would yield?

**Comment by joshuavial** [comment]
Important but not urgent, happy to close this out.
