### ISSUE TITLE
Develop and Turn Richards post on agreements into a Guide to Agreem

### ISSUE THREAD

**Issue by agentlewis** [enspiral/improvements#152]
I was really moved by the post in the rename partners thread https://www.loomio.org/d/pvF9UEJL/comment/1050629

I would love to see a blog about this and possibly the beginnings of a guide to working with enspiral agreements come out of it.

**Comment by agentlewis** [comment]
@joshuavial this may also interest you.

**Comment by rdbartlett** [comment]
Thanks for the prompt Dan, [I've published it](https://medium.com/enspiral-tales/consensus-always-decays-navigating-the-paradox-of-written-agreements-with-care-8af99ad293fe#.onnrktjkj).

If you want to update the handbook, go ahead :)

**Comment by agentlewis** [comment]
@rdbartlett Ah sweet. 

Thanks for tagging it back to me. I will seek some advise about the guide and than make a first draft.
