### ISSUE TITLE
Facilitated Cobudget

### ISSUE THREAD

**Issue by charleydavenport** [enspiral/improvements#154]
in Foundation Cobudget, there is currently ca. $12k of funds in contributor's accounts that aren't being spent. Why is this?

There is ca. $1,351 funds sitting in individual's accounts that haven't yet signed in. In Ops, we periodically (on an ad-hoc basis) Resend-invites to those contributors who have not yet signed in, but I think a better solution might be in the onboarding process for the buddy to specifically have a chat with the new contributor about signing into Cobudget, as they'll have funds there to spend! 

Another issue seems to be individuals hanging onto funds. Is this because there aren't projects people want to put money towards? This isn't really a technical problem apart from funds locked up in user's accounts that haven't signed in, but is something I think should be looked at and addressed to clear the arteries and get the blood flowing in this system. Thanks!

**Comment by joshuavial** [comment]
I think we should make a simple rule such as
- if an account is inactive for 2 months we email the owner with a notice
- if inactive for 3 months we sweep the funds into a collective pool
- all the inactive funds are evenly distributed amongst the active accounts

If folks agreed on this then I would suggest we just code the behaviour into cobudget so an admin can press a button called 'sweep accounts' which does the emailing and sweeping

**Comment by mdshearer** [comment]
From Ops perspective, that would be great for us (as long as inactive funds distribution is actually automated, it'd not be fun to do manually).
This seems like the kind of problem many Cobudget groups would have too.

**Comment by joshuavial** [comment]
Have started a conversation at https://www.loomio.org/d/6PaGwQhO/inactive-cobudget-funds

**Comment by joshuavial** [comment]
- [ ] get input on process
- [ ] draft process 
- [ ] get feedback, rinse and repeat
- [ ] update handbook with process

**Comment by joshuavial** [comment]
Pressing pause on this until #208 is sorted

**Comment by jessykate** [comment]
Woo! It feels like there are a few things to tease apart here. There should be a feature in cobudget that allows reclaiming of funds, which we'll need to put some design thinking into. There are also policy decisions for Enspiral regarding how we would want to _use_ said features. 

I'm down to have a go at stewarding this process. I'll do my best to create a useful/appropriate separation of concerns...  @mdshearer is there a timeline/urgency on this (eg. end of the fiscal year)? Or just generally a desire not to have $12k sitting around aimlessly? 

I'm not sure this is one-sprint ticket FWIW, not sure how y'all handle that right now?

**Comment by jessykate** [comment]
renamed this to ticket with a clearer (to me) name, holler if you don't like it :).

**Comment by mdshearer** [comment]
@silviazuur ^ Jessy-Kate's question about urgency of outstanding funds in Cobudget...? I can't remember if we discussed this yesterday?

**Comment by joshuavial** [comment]
@jessykate any updates on progress or expected timeline?

**Comment by jessykate** [comment]
i have started fleshing out the policies and parameters, and seeking input, in #cobudget channel in slack. i am going away this week until september 3 and should have a document ready by then outlining the  key parameters that need to be decided. 

i am also waiting to hear back from ops on this comment: https://enspiral.slack.com/archives/C03C8G7SU/p1503426915000260. i am happy to mark all these funded buckets as complete, and let ops handle the rest, but would love get an endorsement from you @mdshearer @charleydavenport so i know we're all on the same page.

**Comment by jessykate** [comment]
update: the parameters and policies have been proposed. all buckets has been cleaned up and funds freezed. the next steps are to take the proposal to loomio. my goal is to start the round by the 15th and (as proposed) it would run for a month!
