### ISSUE TITLE
Venture's quarterly updates

### ISSUE THREAD

**Issue by rdbartlett** [enspiral/improvements#164]
- [x] Start [Loomio thread](https://www.loomio.org/d/YaIK15kN/quarterly-reporting-2016)
- [x] Remind people to get their updates in

When updates come in: 

* Add them to the [summary doc](https://docs.google.com/document/d/1A642hhaHHoA0oZcwFEJozu9jsaWke4j4GdmOfDrvZ8s/edit?usp=sharing)
* Update the handbook (or invite them to do it themselves)
* Make a comment on the Loomio thread
* Update this list with status, and tick them off once they are totally complete

- [x] Orientation Aotearoa
- [x] ActionStation
- [ ] Chalkle
- [ ] Enspiral Academy
- [x] Enspiral Accounting
- [x] EXP
- [x] Loomio
- [x] Lifehack
- [x] Metric Engine
- [ ] Scoop
- [ ] Volunteer Impact
- [x] MVB
- [x] Catalysts:
- [x] News
- [ ] Ops

**Comment by susanbasterfield** [comment]
I updated the Handbook

**Comment by rdbartlett** [comment]
@susanbasterfield did you update through github or gitbooks? I'm keen to do all updates through github pull requests so we have visibility on changes.

**Comment by susanbasterfield** [comment]
@rdbartlett I'm embarrassed to say I don't know the difference - I just know where to click 🎱

**Comment by rdbartlett** [comment]
I'm guessing you're using the gitbooks method then, which is fine, but the
github method increases transparency. It's documented in the front page,
with video!

**Comment by susanbasterfield** [comment]
this is what I see  
![image](https://cloud.githubusercontent.com/assets/18182541/17087591/d4aeadd8-5261-11e6-9eb6-6e0a38f24c09.png)

**Comment by rdbartlett** [comment]
No I mean the front page of the handbook has the process documented:
http://handbook.enspiral.com

**Comment by susanbasterfield** [comment]
I was wondering if you could tell which process I'm using from that screenshot?

**Comment by rdbartlett** [comment]
I can tell you're not using the process in the handbook :)
