### ISSUE TITLE
Contributor Cohorts

### ISSUE THREAD

**Issue by susanbasterfield** [enspiral/improvements#165]
From Charley's orginal Loomio post:
I'd like to take a moment to share some thoughts I have about the Buddy System and New Contributors.

My context: I've been processing new contributors and assigning buddies as part of Ops for about 9 months now, so feel I've got a good grasp on the mechanics of it. Something I took away and heard a lot at the Summer retreat was the value of the Home Groups and wonder if that could be a good model for how we pool together new contributors in a more purposeful way, rather than being let through the gates to freely frollick in the fields of Enspiral splendour.

A slight tangent (stay with me here): one fascinating observation about the NZ school system is that you start school on exactly your 5th birthday. In the US, we were all bunched together unceremoniously by birthday cutoff dates. In a way, I like the idea that as a new contributor you would be added to a new group on your enpiral birthday onboarding day for at least your 3-month trial period so that you have a smaller arena of relationships to grasp and a group with other new contributors to purposely explore enspiral together.

Perhaps this could even be arranged by season: New contributors who join on Trial:
Sep-Nov 2016: Koanga 2016 contributor group
Dec-Feb: Raumati 2017
Mar-May: Ngahuru 2017
Jun-Aug: Tukurua 2017
Sep-Nov: Koanga 2017 etc.

We have enough statistics to know that within three months there would be a mixed group of ca. 10-20 new trial contributors who would automatically be populated into a smaller group and could meet on a regular basis with a Member or Steward guide / welcoming committee. All kinds of possibilities from here for how these contributor groups operate.

It could be that a different Contributor Cohort is invited to present for 15 minutes at the Catalyst meeting; or the cohort decides to take the reigns in organising specific projects together. Maybe a rule of new cohorts is that they have to have at least one party/shared meal during the first three months.

Another idea: instead of the opting-in contributor's funds going to their personal cobudget accounts, they could choose to have their funds go towards new contributor cohort's group cobudget account and collectively make decisions about projects instead of individually.

Perhaps a group of 3 members could agree to steward these new contributor cohort groups for a particular month and host a fortnightly meeting or something. Maybe this could even be a paid role from buckets for the couple of hours per month spent. It seems like this would be a lot more manageable than tracking 6 different buddies. The format of these meetings could model how everything else is done here: check-in, Q&A about Enspiral, set discussion point on a current loomio threads, exploration of Cobudget projects, closing thoughts and reflection on what the group could do next.

Here is the 'package', so to speak, a new contributor would get upon coming into the Enspiral network, in addition to access to all the regular enspiral tools (slack, loomio, newsletter, private fb group, cobudget, chalkle)

Onboarding Email Series: giving an individual insight to the tools, culture and technical facets of the network
Member Steward: (one-on-one relationship to manage their individual experience of Enspiral)
New Contributor Cohort: meets on a periodic basis in person & via video calls with a cohort steward.
Contributor Cohort Cobudget: after the 3-month mark, those who opt-in after the 3-month trial carry on with their contributor cohort, and they then have a contributor cohort cobudget account to do stuff with, either in addition to or instead of their individual cobudget accounts.
Having read some of the feedback from those opting out, I get a sense that it's a lack of individual purpose or time as being the main reason contributors opt out. Having a set group, or manufactured set of relationships to negotiate from the start might give more meaning to someone new to the network.

**Comment by joshuavial** [comment]
#207 is addressing this
