### ISSUE TITLE
Counselling Bucket Processing Problems

### ISSUE THREAD

**Issue by charleydavenport** [enspiral/improvements#169]
The experiment of running the Counselling Buckets in Foundation and Services has proved to be a worthwhile project, however, there are complications in processing the payments, which would be good to get advice on:

Essentially, Ops is having to track two different balances for each of the counselling buckets: 1) Allocated balance (what is made guaranteed as available to incoming requests; and 2) Actual Balance, once outgoing payments are processed.

We had been updating the Cobudget bucket with the Actual balance, as it didn't make sense to keep updating with the provisional, allocated balance, since requestors are required to complete the form and have Ops check the actual balance. We could keep the Cobudget bucket balance updated with the 'Allocated' balance only, but there are further complications.

A couple of the requestors got provisional quotes for the sessions from a counsellor, which is what determines the Allocated bucket balance, as the process goes. However, the actual incoming invoice from the counsellor differed from the original estimate, which then throws the allocated bucket balance out of whack with the actual bucket balance, and then has to be tracked additionally.

Another complication is having granted an allocation of the bucket to a requestor, but then not having received the counsellor invoice after a lengthy period of time. We have contacted the requestor to see if the counselling sessions and subsidy from Foundation is going ahead, but in effect (as we're getting to the end of the available allocated bucket budget), these requested funds are preventing any further allocations.

Ops has done one iteration of this process and it _mostly_ works, but we would need more time to improve the next iteration of the bucket to account for these types of variations and clarifying how people should make requests for counselling. It seems half of the requestors went by hearsay, over reading the instructions on how it should work.

We also welcome your ideas about whether it's better for the Allocated balance to be displayed in the Cobudget bucket, or the actual balance to be updated (or both!?) 

We want to keep it as simple as possible for everyone, while at the same time tracking the allocated/provisional balance vs. actual balance.

**Comment by mdshearer** [comment]
Also... Ops doesn't really want to get paid money out of this fund to optimise it as that'd take funds away from the very purpose. So, we may need to raise a separate bucket to optimise it.

**Comment by joshuavial** [comment]
@charleydavenport @mdshearer is this still an issue?

**Comment by mdshearer** [comment]
@joshuavial It is but we haven't got to it yet...

**Comment by joshuavial** [comment]
@charleydavenport @mdshearer - is this still on your backlog or should I close it?

**Comment by mdshearer** [comment]
We'll archive this as the counselling bucket has been pretty quiet and easy to manage
