### ISSUE TITLE
Internal Resilience Campaign

### ISSUE THREAD

**Issue by bartdv** [enspiral/improvements#170]
As a way to help people do their best work at enspiral this campaign aims to cultivate curiosity, provide educational resources and raise the level of conversations about ways of progressing personal and group resilience/wellbeing/performance within enspiral.

This is open to conversation, all thoughts and questions welcomed.

**Comment by joshuavial** [comment]
@bartdv do you want to keep this improvement open or should I close it?

**Comment by bartdv** [comment]
@joshuavial I have saved it in my personal list so you can close it here.

**Comment by bartdv** [comment]
i tried to close it but could not figure out how.  Have saved it in my
folder and you can now close it it.

Happy new year mate!

Find me on *Twitter* *@MrBDV <https://twitter.com/MrBDV> & **Instagram* *@MrBDV
<https://instagram.com/mrbdv/>*
