### ISSUE TITLE
Events at Enspiral (document Chalkle process, create Enspiral Calendar)

### ISSUE THREAD

**Issue by rdbartlett** [enspiral/improvements#172]
Last year we had [a big discussion about events at Enspiral](https://www.loomio.org/d/h6oMxHYz), where we decided to use Chalkle, which has [had some success](https://chalkle.com/enspiral?past=true).

At very least, the instructions for how to post events should be shifted from that Loomio thread into the handbook.

Beyond that though, there is some appetite for an improved events system, e.g. a calendar where anyone can see upcoming events.

Some requirements (all optional at this stage):
- documented in handbook
- all contributors have editing access (if it is a Google Calendar we can use contributors@enspiral.com for this)

**Comment by rdbartlett** [comment]
oops, posted too soon.

**Comment by rdbartlett** [comment]
@hailsus I'm wondering if I can assign this one to you?

**Comment by joshuavial** [comment]
@hailsus any updates on this or should I close it out?
