### ISSUE TITLE
Somebody should game

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#174]
let's harvest some engagement on the improvements board by a loomio

**Comment by coopchange** [comment]
do please game this Loomio thread: [how-do-people-find-a-place-to-contribute-where-does-one-plug-in-](https://www.loomio.org/d/NLzDkf0J/how-do-people-find-a-place-to-contribute-where-does-one-plug-in-); I did mention github but is open for emphasizing ^^
