### ISSUE TITLE
Upgrade onboarding systems

### ISSUE THREAD

**Issue by mdshearer** [enspiral/improvements#178]
Onboarding contributors in to Enspiral is still a very manual process. Ops has made it a lot more efficient by linking our google sheets/forms with trello using Zapier, but we need to upgrade our "database" / google sheet system to the next cheapest step.

We've got some solutions in mind and will propose a bucket or reserves funding request to help with this in the next month or so.

**Comment by mdshearer** [comment]
We're 2/3s through this upgrade. Hoping to have finished in the next few weeks. We've got most of the systems sorted, now we just need to do some testing and fine tuning.

**Comment by charleydavenport** [comment]
We're done! ... We'll continue to make some optimisations to the opt-in process as part of our regular Foundation maintenance time. Check out this loomio for more information and links to the new exciting directory and form to update your details: https://www.loomio.org/d/pzdBHCEF
