### ISSUE TITLE
Handbook page for key Ops related forms

### ISSUE THREAD

**Issue by mdshearer** [enspiral/improvements#179]
Its hard to find forms related to onboarding people, changing membership status etc. Adding a page in the handbook somewhere would be great

**Comment by mdshearer** [comment]
Bucket funded: http://cobudget.co/#/buckets/699
We'll start scoping this out in the next week. And we're looking over the improvements board / handbook labels to see if there's anything else that fits in this scope. "Add list of members" seems like a natural fit.

**Comment by mdshearer** [comment]
@rdbartlett @joshuavial I'm wondering about the handbook schema and where the best place is to put our form links...? 2 of them are for members. An Ops page? A Forms page? Put them on the page that relates to the agreement or the guide...?

**Comment by rdbartlett** [comment]
My vision is to refactor the agreements down so each one is a terse set of bullet points, and everything else is a guide. 

I reckon it makes sense to add a "Forms" page as a Guide, plus you could duplicate the links into any relevant existing pages.

**Comment by mdshearer** [comment]
If the links are duplicated and we change a link sometime in the future... is there any new-fandangled way of making sure they all update...?

**Comment by rdbartlett** [comment]
not yet.

**Comment by mdshearer** [comment]
Ok. I've done something real basic. Just to see if I'm on the right track. Created a new forms page but haven't updated the summary page yet. I couldn't figure out how to know what the link to the new page is, if it's currently in my own repo.

**Comment by joshuavial** [comment]
Merged in @mdshearer https://handbook.enspiral.com/forms.html
