### ISSUE TITLE
update venture agreement

### ISSUE THREAD

**Issue by robguthrie** [enspiral/improvements#180]
From board POV we want to ensure that all ventures have some minimal structure to ensure they're responsibly run. 

Things I think a venture need regardless of if they have a hierarchy or not.

Ownership
  clarity of boundaries
    who do I work work for
    do I own this
    am I the boss?
    am I liable?

Management
  CFO - finances are someones job. Everyone can ask questions and get clear answer.
  documentation
    Policies are co-designed
      explicit
      document what you do, rather than what you will do.
      everyone contributes
  Coordination of work
    we use a combination of
      strategy work
      agile
      90 day planning
    distinct spaces for talking about different time scales
      rhythm.
    set objective for given time period then stick to it
  Accountability and Support
    two sides of the same coin
    working in view of your colleagues so they can spot when they need to support you
      eg: standups with wellbeing checkin

Governance
  having a conflict resolution policy
  someone who is close, but not on the inside, that you trust to help resolve difficult situations.
  has an eye on the law.
  knows enough about what the company is doing, to know if it is within the law.
  trusted connected responsbile, prudent,
  very low capacity to actually do anything.

Next steps
Process to upgrade venture agreement to include this?
implement MVS across ventures or shut them down/remove from enspiral

Clarify venture stewards, is it really about having a board?
catalyst to checkup on ventures and identify where people do not have parts.

**Comment by mdshearer** [comment]
@robguthrie Parallel thought to this, which could lead me to raising a bucket. I'm wondering whether Ops should be setting up a venture onboarding system. ie. Some kind of Google form with those questions in it plus a bunch of other processes/systems so nothing gets dropped.

**Comment by rdbartlett** [comment]
Nice idea Malcolm. We're going to catch up with Andre about this on Friday
morning.

**Comment by robguthrie** [comment]
Talking with Gina today. We identified that being a Venture steward could be a lot more formal than a member steward. 

One interpretation is that we develop this checklist as something we expect venture stewards to go through when working with the venture.

**Comment by mdshearer** [comment]
Update from Ops: Ops is going to formally upgrade to proto-venture status but there's a few little gaps in the handbooked process. I've setup a google form to capture all the data requested in the Venture template and once we've gone through the process, we'll update the handbook.

**Comment by joshuavial** [comment]
any update on this ticket @mdshearer

**Comment by mdshearer** [comment]
@joshuavial I missed this question. The original ticket was about the ventures agreement, not sure that relates to Ops directly. We haven't had any new ventures for quite a while so we've held off on improving the system anymore than what it currently is.

**Comment by joshuavial** [comment]
Copy that, closing the ticket in the meantime and we can reopen when someone has energy to tackle
