### ISSUE TITLE
process for announcing when hiatus

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#185]
work with ops to clarify the process for a member stepping back

**Comment by susanbasterfield** [comment]
@mdshearer Hi is there any specific process here other than emailing Ops?

**Comment by mdshearer** [comment]
Sure is. We've been proto-typing a [form](http://goo.gl/enyzHe) in the last few weeks. 
I've setup a bucket to get some funding to do a whole batch of ops edits to the handbook including adding a place for all our forms.
