### ISSUE TITLE
An app for making nonhierarchical org charts

### ISSUE THREAD

**Issue by rdbartlett** [enspiral/improvements#188]
I'm thinking about doing a little hobby project to build a basic app for making nonhierarchical org charts. 

I'm looking for a developer who would like to explore this with me.

Here are three examples of what I have in mind:

![Functional org chart](http://loomio.coop/workinggroupsQ2-2016.png)

![Loomio stewards](http://loomio.coop/img/stewards2016.png)

![Enspiral stewards](http://handbook.enspiral.com/images/steward-chart-sept-2016.png)

**Comment by ahdinosaur** [comment]
oh hey @rdbartlett, i may or may not have ideas here. as in, [making non-hierarchical charts in one the value propositions @simontegg and i were working towards with holodex](https://github.com/holodex/holodex/blob/master/comms/value-propositions.md), and [i still want such an app to exist](https://github.com/holodex/app/). :cat:

**Comment by rdbartlett** [comment]
Nice one, thanks for the ping @ahdinosaur. I'm also keen to jam with @will-sklenars on this.

The app I have in mind is something like: simple interface for uploading information about people + relationships -> generates cool visual graph. 

The main value prop is just to make it easy to produce org charts that we need to run orgs like Enspiral and Loomio.

I'm not sure how to evaluate if it would be easier to start from scratch (informed by what you learnt from holodex), or to keep developing holodex so that I can use it. What do you reckon?

[This view](http://holodex.enspiral.com/groups/loomio?q%5B0%5D%5Blink%5D=%2FlinkTypes%2Fhas-member&q%5B0%5D%5Bsrc%5D=%2Fgroups%2Floomio&q%5B1%5D%5Blink%5D=%2FlinkTypes%2Fis-subgroup-of&q%5B1%5D%5Bsrc%5D=%2Fgroups%2Floomio&q%5B2%5D%5Blink%5D=%2FlinkTypes%2Fstewards&q%5B2%5D%5Bctx%5D=%2Fgroups%2Floomio&q%5B2%5D%5BshowLink%5D=true) is pretty cool, I just don't know anything about the editing interface: 

![image](https://cloud.githubusercontent.com/assets/970124/18453710/a8997660-7994-11e6-8962-92eeb48bacd3.png)

**Comment by ahdinosaur** [comment]
> I'm not sure how to evaluate if it would be easier to start from scratch (informed by what you learnt from holodex), or to keep developing holodex so that I can use it. What do you reckon?

i've learned for me it's almost always easier (and much more enjoyable) to start from scratch than try to adapt something (especially if it contains technical debt) to fit a particular use case. during my time off i re-wrote the technical side of holodex: https://github.com/holodex/app/, but even that is only as useful as the person who wants to work on this thinks.

**Comment by will-sklenars** [comment]
Maybe we should try nut out some of the specifics of what kind of data we want to represent, and maybe some different ways we could visualise it? That process might help to judge weather to use holodex or start from scratch.

Could be interesting to think about some 3d designs too.

**Comment by rdbartlett** [comment]
When I draw images like this I always get people asking "is there an app that can make these?" and I have to say "no, it is a time consuming manual process using expensive proprietary software" :(

**Comment by rdbartlett** [comment]
Currently being discussed in #NetworkMap on Slack
