### ISSUE TITLE
Check our agreements match reality

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#191]
Propose an omnibus of small changes to keep our agreements in line with what is happening:
* Remove Cobudget role from Catalysts
* Remove steward requirement on catalysts (assuming stewardship is going to roll out further after our 6-month review at the Members Retreat)
* Trim excess out of agreements into guides

**Comment by susanbasterfield** [comment]
I'm noodling in the hackpad https://hackmd.io/KwZghgxg7CwCYFoAcI4E4EBYBmcLJAEYAjBYgUwgAYrhjM8wqg==?view

**Comment by susanbasterfield** [comment]
please review https://docs.google.com/document/d/1eO8kAlau_p9meYd3-YQiQAZJS_X3ASQXa-agn0Qhn5U/edit#

**Comment by rdbartlett** [comment]
In progress here: https://www.loomio.org/d/5E2XA6pt/updating-our-agreements

**Comment by rdbartlett** [comment]
I'm intending to put up some proposals in that thread pretty soon - this week if I get space.

**Comment by joshuavial** [comment]
#325 solves the biggest need for me so I'll be closing this in the next few sprints unless someone else wants to pick it up
