### ISSUE TITLE
analytics on handbook

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#193]
https://www.npmjs.com/package/gitbook-plugin-ga

**Comment by phillcoxon** [comment]
@joshuavial - can you add me as a user to Google Analytics so I can add a new property & get a tracking id to use?

**Comment by joshuavial** [comment]
apologies for the delay @phillcoxon, I thought I had done this - have added you to google analytics now.

**Comment by joshuavial** [comment]
@phillcoxon any updates?

**Comment by phillcoxon** [comment]
Thanks for the reminder.

Adding it to my todo list to review & action this week.

**Comment by phillcoxon** [comment]
Pull request https://github.com/enspiral/handbook/pull/110

**Comment by phillcoxon** [comment]
Analytics are now being collected on the handbook.  From here we'll be able to craft some custom reports to explore how the handbook is being used. 

![](https://i.imgur.com/ae23cwC.png)
