### ISSUE TITLE
blog.enspiral.com is broken

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#201]
http://blog.enspiral.com/ redirects to http://blog.enspiral.com/cgi-sys/defaultwebpage.cgi

It should redirect to https://medium.com/enspiral-tales

**Comment by joshuavial** [comment]
Anyone up for looking at this @agentlewis @phillcoxon ?

**Comment by agentlewis** [comment]
@joshuavial I'll look into this.

**Comment by joshuavial** [comment]
It's working now - thanks if you did anything @agentlewis

**Comment by agentlewis** [comment]
@joshuavial na i didn't - i looked into it and determined that it is using a redirect on a non linode server. i suspect its one phil has set up as there are several domains using the same ip.

**Comment by agentlewis** [comment]
I have created a new ticket to pick up, standardise and document how we are doing redirects.
https://github.com/enspiral/improvements/issues/203
