### ISSUE TITLE
Propose member circles idea

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#208]

**Comment by andrebate** [comment]
Suggested process
-Written doc from growth working group to members
-Invitations for members to respond with videos (with growth working group having a starting working group)
-Videos and doc go up on Loomio before Christmas
-From Jan 15 - have a small group discussion before summerfest

**Comment by rdbartlett** [comment]
My notes from our catch up last week:

"Member-Contributor circles have been critically important to network structure, balancing space for inclusion with space for deep commitment and trust. Contributor is someone one member trusts, member is someone all members trust. Problem is the member circle doesn’t scale effectively beyond ~20-30 people. So we’re looking for a new structure that preserves what's important but with more room for growth.

Working proposal: Let’s have multiple member circles. Membership is first about belonging and support. With the consent of their circle, a Member can opt into a Delegate role who can block network agreements, decide whether circles exist."
