### ISSUE TITLE
Working Groups Agreement

### ISSUE THREAD

**Issue by susanbasterfield** [enspiral/improvements#215]
Working Groups are documented here: https://handbook.enspiral.com/working-groups/

Time to host a discussion and make a Working Groups Agreement.

**Comment by rdbartlett** [comment]
I've started documenting the working group process here:

https://hackmd.io/AwRgbATGDGCsAsBaARgM2AE0fe0SIE5hUJFIB2DMYMZAZgIENUg=?both

I think once we have a few more groups running on this process, we should start a network-wide thread about it.

**Comment by rdbartlett** [comment]
I'm keen to rename the Catalysts to the Catalyst Working Group soon, and rename the Slack channel and Improvements label to 'WG-Catalysts'

**Comment by joshuavial** [comment]
I'm up for that name change @rdbartlett

**Comment by rdbartlett** [comment]
This is under discussion here: https://www.loomio.org/d/lfVWaqEj/working-groups

Not hearing great enthusiasm to make a new agreement just yet. People already kinda take working groups for granted. My plan is to keep moving this very gently forward and propose an agreement in a month or two.

**Comment by joshuavial** [comment]
Having a chat with @susanbasterfield and we're not feeling the need for an agreement - having more info in the guide would be great but we're not sure what needs agreeing to right now and suggest closing this ticket
