### ISSUE TITLE
Sort out cobudget taxation issues

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#221]
Some cobudget funds are not income, they are gifts. 

The guidance we got from deloitte was that the license fees businesses and contributors pay is legit as an expense (gst, treated as taxable income for the foundation)

Gifts above and beyond that (arbitrary payments from individuals or ventures) are gifts which are post tax for the giver and untaxed for the foundation. 

This means that the money that comes into the foundation is a mix of gift and income and the expenses that go out are a mix of deductible and non-deductible

**Comment by jessykate** [comment]
i'm not sure this is a just cobudget issue but more of a general contributions issue (but relates to cobudget as the mechanism for spending those contributions). FWIW @silviazuur is working on this this month as part of a suite of wg-financial tasks. 

perhaps useful to separate this into how we give people receipts, and then how we document our own spending of those funds. are those separate tickets? my impression is that silv is working initially on the former.

**Comment by joshuavial** [comment]
@jessykate happy for you to delete, split, morph or anything else you would like to do to this ticket.

**Comment by joshuavial** [comment]
This is being covered in #331
