### ISSUE TITLE
Contributions Working Group

### ISSUE THREAD

**Issue by rdbartlett** [enspiral/improvements#223]
At the October Members meeting, Sam, Malcolm, Susan, and Rob volunteered to form the Contributions Working Group, to take the Board's recommendations about Foundation finances and facilitate them to a final conclusion. 

I said I would support the WG to use the Improvements board to track their work. Here we are!
- [x] Make tickets for each recommendation.
- [x] Set up Slack channel.
- [x] Call first meeting.
- [ ] Track progress here and include an update in the newsletter.

**Comment by rdbartlett** [comment]
I'll make tickets for the 6 recommendations, and label them WG-Contributions so you can find them.

**Comment by rdbartlett** [comment]
You can find the tickets for the recommendations here: https://waffle.io/enspiral/improvements?label=WG-Contributions

I've carved off the Hardship Working Group as it's own ticket (#222), out of scope for the Contributions WG.

**Comment by susanbasterfield** [comment]
Loomio has been raised for first proposal
