### ISSUE TITLE
Refactor individual contributions to Foundation

### ISSUE THREAD

**Issue by rdbartlett** [enspiral/improvements#226]
Recommendation from Board:

Set individual contributions to a base membership fee of $100/yr(+gst), add $90(+gst) if you want to use Google apps, add anything you’d like to spend in Cobudget. Currently we split all income 50/50 between admin and Cobudget, which a) feels like a tax when you want to contribute to something cool in Cobudget and b) is a passive way of contributing so many people have cash in Cobudget but don’t know they have it there to spend.

Contributions WG going to host a decision about this.

**Comment by coopchange** [comment]
Any updates on this? I know @silviazuur mentioned that this was still backlogged in conversation to Mieke about Phoebe Tickell's Summerfest bucket

**Comment by silviazuur** [comment]
Yup we are meeting about it on Friday at NZ9am

**Comment by jessykate** [comment]
isn't this complete?

**Comment by silviazuur** [comment]
Yeah I would say complete!
