### ISSUE TITLE
Enspiral as a DDO (deliberately developmental organisation)

### ISSUE THREAD

**Issue by susanbasterfield** [enspiral/improvements#229]

**Comment by fuzzytern** [comment]
Curious. @susanbasterfield  Could you provide more insights into what that means or the vision behind it?

**Comment by jessykate** [comment]
_loooove this_, whatever it is :).

**Comment by joshuavial** [comment]
@susanbasterfield any plans on moving this forward or should I archive it?

**Comment by chime-mu** [comment]
Before you kill it @susanbasterfield, I'd be interested in a brief conversation around your thoughts. In some sense I guess Enspiral is a DDO - so what would be the next (small) step in your mind?

**Comment by susanbasterfield** [comment]
sure @chime-mu I think that Enspiral is a non-practicing DDO - it's part of our DNA but we are not claiming it, if that makes sense.  As we've discussed, a DDO is simply a frame for recognising that most of the fodder we need to do our ongoing personal development is available to us through our work. The more I work in this sphere, the more convinced I am that this acknowledgement and opportunity is a 'missing link' to transitioning or sustainably flat organisations.  So @joshuavial please leave it in the backlog, maybe someone will pick it up

**Comment by phoebetickell** [comment]
@susanbasterfield could we think of an actionable next step to claim being a practising DDO? What would success look like as an end product if we claimed this? Does it take a blogpost, or integrating shared practises, or a new rhythm? Curious :)

**Comment by joshuavial** [comment]
@phoebetickell @susanbasterfield is this still underway or should I close it?
