### ISSUE TITLE
Updating Enspiral Handbook Events Page

### ISSUE THREAD

**Issue by charleydavenport** [enspiral/improvements#231]
In reviewing: https://handbook.enspiral.com/events.html

I've noticed this needs to be updated to include the ongoing current resources for Enspiral Events, such as EXP retreats, Open Enspiral Workshops etc. Ops is doing update work to the Handbook, but this is a page we're not sure what the answer would be.

In the Foundation Helpdesk, we receive approximately 1-2 messages per week from random people wanting to keep up to date with Enspiral events, but there's not one specific place to direct them to. (Some have responded to say that they will not regularly check a static website and are not FB or Twitter users.)

**Comment by phillcoxon** [comment]
Update:  this URL is now showing a Page Not Found page.

**Comment by joshuavial** [comment]
This page was removed when we migrated away from chalkle
