### ISSUE TITLE
broken link on enspiral.com

### ISSUE THREAD

**Issue by ahdinosaur** [enspiral/improvements#232]
hey all :cat: 

i was reading the [enspiral.com FAQ](http://enspiral.com/about-enspiral/faq/) when i noticed this, within the "How do people get involved?" section

![snapshot78](https://cloud.githubusercontent.com/assets/719605/19883958/f1c64b02-a07b-11e6-9bcc-6c1b88783da0.png)

i click "here", then i get

![snapshot79](https://cloud.githubusercontent.com/assets/719605/19883936/d1c99fca-a07b-11e6-836a-e18febd5423c.png)

it feels like a TODO was left undone, but i have no idea, so here i am with a bug report. :bug:

**Comment by phillcoxon** [comment]
Thanks @ahdinosaur.  Nice spotting. 

I've updated the page to remove the "CHECK THIS LINK" and changed the hyperlink to point to the Handbook People Agreements page for the moment.  Happy to adjust further if there are better suggestions.

**Comment by ahdinosaur** [comment]
@phillcoxon nice! seems legit to me, i'll close the issue until anyone wants to re-open it. :smile:
