### ISSUE TITLE
SEWF 2017 Promotion

### ISSUE THREAD

**Issue by susanbasterfield** [enspiral/improvements#239]
SEWF looking for "channel partners" basically to help promote the forum via our network.

In return, they're looking to provide a number of discounted tickets for people in Enspiral.

Is this something that could be run through the Foundation and if interested, could I forward a contact person onto Helene?

**Comment by silviazuur** [comment]
I'm gonna meet Helene on Wednesday to talk about this - so could be added to this ticket and have it removed from stale

**Comment by joshuavial** [comment]
are there any updates on this ticket @silviazuur @susanbasterfield or are we ready to celebrate/archive?

**Comment by silviazuur** [comment]
Yup its been confirmed. Posted in Enspiral News. And Jess will be promoting
on FB.










*   Silvia Zuur         Enspiral Foundation <http://www.enspiral.com>:
Member and DirectorEXP <http://www.exp.agency/>: Directorwww.silviazuur.com
<http://www.silviazuur.com>c/o Dev Academy, Level 2, 275 Cuba Street Te
Aro, Wellington 6011Phone 022 0126 366          Skype silviazuur *
