### ISSUE TITLE
update github users

### ISSUE THREAD

**Issue by genevievebelle** [enspiral/improvements#245]
github switched pay per user rather than no. of repositories a while ago so we're probably been hit with a unnecessary large subscription bill to include users who are no longer contributors.

My suggestion is that Ops ensure the membership list matches current contributorship and add github to their offboarding check list :)

**Comment by mdshearer** [comment]
@joshuavial Do you know if this is the case...? Are we getting charged for every user or do we have a grandparented deal...?

**Comment by joshuavial** [comment]
@mdshearer we are on a grandfather plan where we are not charged on a per user basis (services pays the bill). Once I get rid of all our private repos we will switch to the free plan.
