### ISSUE TITLE
Clarify process for bit-by-bit buckets

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#25]
This ticket was originally a question about rolling buckets which has mostly been resolved (by avoiding them).

There is still an unresolved issue with how to reconcile a bucket which is paid out a little bit at a time with my.enspiral

**Comment by susanbasterfield** [comment]
@mdshearer what are your thoughts on this?

**Comment by mdshearer** [comment]
Haven't had much capacity to look in to it but Ops is getting closer to having some capacity. Jamming on cobudget improvements sounds like a good idea.

**Comment by joshuavial** [comment]
@mdshearer is this still an issue or have you figured this out?

**Comment by mdshearer** [comment]
We're paying out the counselling bucket bit by bit and I haven't heard any other discussion about this being a problem recently.

**Comment by susanbasterfield** [comment]
@mdshearer are you happy then for us to celebrate and close the ticket?

**Comment by mdshearer** [comment]
I didn't open this issue but, sure, Let's complete this.
