### ISSUE TITLE
Edit enspiral.com so it renders with an addblocker

### ISSUE THREAD

**Issue by Camcan** [enspiral/improvements#253]

**Comment by phillcoxon** [comment]
Hi @Camcan - can you give more detail please? I have Ad Block Pro running and Enspiral.com seems to render just fine. What os / browser / adblocker are you using?  Are you able to attach a screenshot?

**Comment by Camcan** [comment]
@phillcoxon  - Whoa; holy quick-reply batman!
Where's best practice to upload a screenshot? Essentially everything except what's in the footer appears blank & grey.
It's Ghostery that blocks calls for the scripts (in Chromium), giving a whole stack of "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" in the console. I'm running Ubuntu 14.04 on this box.

**Comment by phillcoxon** [comment]
You can drag and drop screenshots into this comment area or paste from the clipboard. 

Are you able to try from Google Chrome and see if you still get errors to determine if it's Ghostery itself or the combination of Ghostery & Chromium but works with other browsers?  Also indicate what resources are being blocked in the console log?

**Comment by phillcoxon** [comment]
Ping @camcan
