### ISSUE TITLE
Move to recurring financial contributions

### ISSUE THREAD

**Issue by jessykate** [enspiral/improvements#257]
For compliance reasons we understand this will need to be designed as a set of specific membership "levels". 

- Dan (agreements, board, taxes)
- JV (ops, form, xero, process)
- Susan (contributor comms & engagement) 

- [x]  decide on what the levels should be (minimum level being the current annual level)
- [x]  research and select a subscription tool that would do automatic billing so that ops is not chasing down unpaid invoices (madness lies here).

Dan and JV's todo list
- [ ] draft the form (sprint 34)
- [ ] create amendment to financial agreement
  - [ ] update income section
- [ ] amend board agreement for more clarity around haircutting cobudget
  - [ ] delegate board powers to haircut cobudget to pay tax
  - [ ] board has power to pull funds from cobudget if core accounts are low
- [ ] work with ops to create a process guide on how financial contributions are managed
  - [ ] creating new ones
  - [ ] changing old ones
  - [ ] deactivating old ones
- [ ] loomio agreement on new process

**Comment by joshuavial** [comment]
So excited about this change, I think it will have significant positive impacts on the network.

**Comment by joshuavial** [comment]
this is being picked up by some wg-gsd folks as part of #301

**Comment by danalexilewis** [comment]
Have a WIP pr: https://github.com/enspiral/handbook/pull/108/files

**Comment by danalexilewis** [comment]
I have moved my work onto venture contributions #356 - I feel this work has been covered by ants, bart, phill and ops.

**Comment by mdshearer** [comment]
Update. We finished this!
