### ISSUE TITLE
Make an Enspiral finances guide

### ISSUE THREAD

**Issue by jessykate** [enspiral/improvements#259]
There are several constraints and requirements related to how we operate financially. These often confound people and are the subject of much folklore, exaggeration, FUD, etc. 

If we laid them out clearly, it would make working with and on our financial systems much more accessible (and FUN!). 

ref: these notes that Silvia took at the summer fest in feb 2017: https://docs.google.com/document/d/1ZhtYZJouloqLSXJ-l5m7gNMHnE9TmlRSFXyrKU0Lhk4/edit?ts=58b24d9d

include relevant considerations and compliance requirements for money coming in to, or going out from, different categories (recurring, one off, domestic, international, business expenses, personal expenses, etc.).

**Comment by phoebetickell** [comment]
@jessykate could this relate to #247?

**Comment by jessykate** [comment]
yes! and also #281. should we collapse them? i guess the question is whether we want a guide that is separate (if linked) from the handbook pages on cobudget and enspiral finances. i think we could start with one thing for now and split it out if that feels necessary. any objections to combining them all into one ticket?

**Comment by joshuavial** [comment]
My suggestion is to close this one @jessykate and focus on the cobudget one as it's more specific

**Comment by jessykate** [comment]
agreed, i'll close this and tweak #247.
