### ISSUE TITLE
Enspiral.com tweaks

### ISSUE THREAD

**Issue by phillcoxon** [enspiral/improvements#260]
- [x] switch google analytics to https:// after let's encrypt SSL upgrade
- [x] update [Enspiral Services venture page](https://enspiral.com/ventures-and-teams/enspiral-services-limited/) which is still incomplete
- [x] confirm removal of Rabid as a venture on the site now they are moving to "friend of" status

**Comment by phillcoxon** [comment]
@joshuavial - do you have the analytics account for Enspiral.com?  Are you able to update the property settings to use https:// instead of http://.

**Comment by joshuavial** [comment]
Done @phillcoxon - do you need the tracking id?

**Comment by phillcoxon** [comment]
@joshuavial - the tracking id won't have changed so that's all good. Analytics should be picking up tracking again now.  Thanks!

**Comment by joshuavial** [comment]
@phillcoxon how are we going with this?

**Comment by phillcoxon** [comment]
@joshuavial - I have disabled Rabid as a venture and have also disabled the Services page until if/when it gets updated. So all done.
