### ISSUE TITLE
Decide what e-mail or phone for 'Harrasment/Abuse Hotline'

### ISSUE THREAD

**Issue by coopchange** [enspiral/improvements#268]
ATTN: MVB

As WWG is near to a Request For Comments/ Proposals with the current draft of a Personal Conduct Agreement (i.e. Code of Conduct + ), we're keen to know what e-mail we could list for emergencies (besides external authorities, naturally).

Draft's linked; we'll be making an official ask of the network to co-edit/ comment just after the 20th. Thanks!

https://docs.google.com/document/d/1imAamOKSoqpCHnrsM8U2CWuZTrmOo5WYkqsVYETG_fk/edit?usp=sharing

**Comment by coopchange** [comment]
the guidelines are also of note as they will include the recommended escalation-steps, and thereby will affect the frequency that the contact information provided is utilized. [Conflict Resolution Guide](https://docs.google.com/document/d/1FElHGHgQ39u_z1QWCbzJQozvoILAH7hjL1_g2waEJVs/edit?usp=sharing)

**Comment by coopchange** [comment]
@robguthrie @silviazuur - we've put directions to email foundation@enspiral.com in the [Personal Conduct Agreement (final draft)](https://docs.google.com/document/d/1imAamOKSoqpCHnrsM8U2CWuZTrmOo5WYkqsVYETG_fk/edit?usp=sharing) that is what we'll be putting before the network in the next few weeks

**Comment by susanbasterfield** [comment]
approved within the code of conduct agreement
