### ISSUE TITLE
More catalyst details in handbook.

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#27]
Add much more fleshed out narrative about the thinking behind Catalysts to the Handbook, separate to the Agreement

**Comment by rdbartlett** [comment]
I've started sketching here:
https://hackmd.io/KwZghgxg7CwCYFoAcI4E4EBYBmcLJAEYAjBYgUwgAYrhjM8wqg==

**Comment by susanbasterfield** [comment]
I've been noodling there too

**Comment by rdbartlett** [comment]
Here it is: https://github.com/enspiral/handbook/pull/65
