### ISSUE TITLE
Publish stories from Korea trip

### ISSUE THREAD

**Issue by rdbartlett** [enspiral/improvements#278]
I have 2 workshop reports nearly ready to go, and hopefully a 3rd article from a brilliant conversation with Dr. Seoungwon Lee.

**Comment by joshuavial** [comment]
Is this still in progress @rdbartlett ?

**Comment by rdbartlett** [comment]
Done:

https://medium.com/enspiral-tales/impeach-the-boss-b9d7a88d8411
