### ISSUE TITLE
Launch Contributor Activation Programme

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#288]
- [x] decide on initial challenges
- [x] decide on success criteria
- [x] create spreadsheet for tracking challenges
- [x] recruit initial participants
  - [x] create loomio thread with invite
  - [x] decide on a deadline for starting trial
- [x] write something in the handbook

**Comment by joshuavial** [comment]
Initial thoughts on challenges

Easy
- write a blog post
- update the handbook
- create an improvement ticket
- join a working group
- attend an in person enspiral event
- interviewing an old timer
- give feedback on the activation programme

Intermediate
- create a bucket in cobudget
- get paid from a bucket
- complete a ticket (alone or with someone else)

Harder challenges
- steward a new contributor through the activation programme 
- find paying work for someone enspiral

**Comment by marionbedat** [comment]
Here is an updated version of the challenges, including feedbacks from Ants

1. Easy challenges
> Enspiral processes
- update the handbook
- create an improvement ticket
- join a working group
- give feedback on the activation programme

> Enspiral people
- attend an in person enspiral event
- interviewing an old timer

> Enspiral culture and ideas
- write a blog post
- create a loomio thread
- share something that excites you on Facebook group/slack channel

2. Intermediate
- create a bucket in cobudget
- get paid from a bucket
- complete a ticket (alone or with someone else)

3. Harder challenges
- steward a new contributor through the activation programme
- find paying work for someone enspiral

**Comment by marionbedat** [comment]
Another comment on how to prototype and test this new process:
- Involve the stewards as soon as possible to collect their feedback, make them appropriate the challenges and be able to encourage/support new members, and benefit from their support to recruit the very first participants for testing
- In the video, it will be key to explain to the new members that these challenges are part of "learning by doing" onboarding process.

**Comment by joshuavial** [comment]
@marionbedat and I are meeting tomorrow to create a video and kick off a loomio process.

**Comment by joshuavial** [comment]
We are planning on kicking off at the beginning of sprint 30, loomio inviting initial participants will go out next week. @marionbedat is working on the handbook page (and completing a challenge in the process) and I'll post the loomio thread. 

We will be holding fortnightly checkin threads in slack and tracking engagement with a monthly survey.

**Comment by joshuavial** [comment]
I'm calling this ticket done and will create another one for reflecting on the experiment
