### ISSUE TITLE
Development of Improvements list

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#30]
- [x] setup github issues
- [x] private beta
- [x] loomio of public beta
- [x] complete public beta
- [x] loomio decision on public or not
- [ ] write up in handbook
- [ ] work with ops to update onboarding / offboarding process

Key metrics to evaluate the experiment
- number of issues flowing through the system
- number of people engaged with the system

**Comment by joshuavial** [comment]
@mdshearer what changes are needed from ops to finalise this ticket? I'm thinking that we should include a step in offboarding where ops removes a person from the contributors team in github.

I also wouldn't be adverse to some kind of change in our welcome emails to contributors that mention http://improvements.enspiral.com and tell people to post in #improvements on slack if they want to be given write access to the board.

Anything else needed from your end?

Once we've got the ops changes sorted the last piece of work is to update the handbook and we're good to go.

**Comment by mdshearer** [comment]
Sounds good. Do people get onboarded by asking...? ie. We don't onboard we just offboard right?
Can't think of anything else right now.
