### ISSUE TITLE
Link bug on enspiral.com

### ISSUE THREAD

**Issue by SlimeyD** [enspiral/improvements#300]
Visiting the enspiral website through Firefox/MacBook Pro. When I click on the 'Enspiral Handbook' link it takes me to the github page for the handbook. Not the Enspiral Handbook on gitbook

**Comment by SlimeyD** [comment]
Here's the bug @phillcoxon

**Comment by phillcoxon** [comment]
@SlimeyD 

The handbook link in the footer is redirecting to http://handbook.enspiral.com/ for me just fine. Tested in multiple browsers.

Would you please open up a private firefox session and test again.  Also test in chrome. It may be a cached 301 redirect in your browser from some time ago.  If so you'll need to clear your browser cache to get rid of it. 

Let me know if that makes a difference. 

Thanks in advance, 

Phill

**Comment by SlimeyD** [comment]
Thanks Phill, It was through someone else's browser but I've asked them to clear their cache and see if it that helps. Will clear off this ticket if so

**Comment by SlimeyD** [comment]
They cleared their cache  in firefox and still got the same result

**Comment by joshuavial** [comment]
@phillcoxon I can confirm that I'm getting the same result as Damian's friend - the link on the home page to the handbook (orange box) takes me to the github page.

**Comment by phillcoxon** [comment]
Ah! Now I see. I was looking at the footer.

Fixing now.
