### ISSUE TITLE
Balancing the Books

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#301]
decide on a course of action based off the balancing the books conversation

**Comment by joshuavial** [comment]
- [ ] design a work flow from a contributors point of view
- [ ] letter announcing the change
- [ ] proposal go up to the network for an individual contributions agreement
- [ ] work with ops to establish and support the new workflow

**Comment by bartdv** [comment]
Hi Josh,

What is this?

Find me on *Twitter* *@MrBDV <https://twitter.com/MrBDV> & **Instagram* *@MrBDV
<https://instagram.com/mrbdv/>*

**Comment by joshuavial** [comment]
I'm closing this ticket as it has been turned into a working group with lots of sub tickets
