### ISSUE TITLE
overhaul new contributor welcome emails

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#318]
https://www.loomio.org/d/VmLoYapI/comment/1427099

**Comment by charleydavenport** [comment]
Howdy all - when  I get a chance, I'll report back here with a working Google doc for feedback and comment on the current Onboarding Comms. Once the revised text is finalised, Ops can update the Mailchimp emails to reflect the new text with links etc.

One goal of the improved text, apart from being more accurate, is to include features of the Contributor Activation Programme, so we'll potentially seek any feedback from that working group.

**Comment by charleydavenport** [comment]
All Mailchimp emails have been edited with new text, images and links. Next step will be incorporating these text changes into the Handbook.

**Comment by joshuavial** [comment]
Love your work @charleydavenport

**Comment by charleydavenport** [comment]
Okay! We can Celebrate this job: all updates have now been added to the handbook: https://handbook.enspiral.com/guides/onboarding-info.html

No doubt this will be something we revisit from time to time as Enspiral evolves and we find more ways to supplement onboarding contributors to the network.
