### ISSUE TITLE
"Invitation: Co-inquiry on Peer Support" +/- social bookmarking thread for such initiatives (formerly: channel for Stewards to discuss learnings...)

### ISSUE THREAD

**Issue by coopchange** [enspiral/improvements#320]
Could be a mirror channel to #activation-programme or #stewardingv2, or a Loomio thread to kick it off... @sanchemin @bernhardre  @lucasexpresso and I talked about this during the Engagement break-out of the GSD (formerly ~Delegates~) working bee; [some relevant notes here](https://docs.google.com/document/d/1-tbJ8yw7o5xrCK3blPwbQenvibLerMPs7fwLGIl-f5U/edit?usp=sharing#heading=h.qbd0hw473j3o)

**Comment by phoebetickell** [comment]
Maybe something to discuss on the stewardingv2 call @coopchange? Would love to hear more about why you think this would be useful and also how it responds to the stewarding survey Rich carried out. It'll be great to get some strategic thinking done on how best to reboot the system :)

**Comment by coopchange** [comment]
+1 @phoebetickell  -- I am intrigued by starting a Loomio thread on Best Stewarding Practices, but I want to garner some energy in advance, and maybe a better way to open source our learnings and grow each other as stewards will emerge.

**Comment by coopchange** [comment]
Simon Jarvis started a nice [Loomio on stewarding best practices](https://www.loomio.org/d/kAI8urWa/what-makes-a-great-stewarding-practice-)

Next steps are to 
- [x] spark and weave some people into that conversation, 
- [ ] feed it into the handbook at the end, 
- [ ] set a reminder to revisit the conversation somewhere 6mo to a year later.

**Comment by coopchange** [comment]
Updated to include the action from the Members meeting in July 2018

**Comment by coopchange** [comment]
New approach with following subtasks:
- [ ] get Nati and/or Sandra feedback on Loomio
- [ ] post and facilitate conversation in the Loomio
- [ ] move on to #515
