### ISSUE TITLE
clarify intentions of all catalysts

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#327]

**Comment by susanbasterfield** [comment]
@rdbartlett will step back in to full service upon his return, and I will tag out at that stage

**Comment by rdbartlett** [comment]
I'm in South American for October and probably November, so timezones will be more conducive to me meshing more closely with Catalysts. When i get back to NZ I expect to be more available to be the rhythm keeper, with the proviso that I would like to have some pretty decent holiday time in there too.
