### ISSUE TITLE
Google apps account reconciliation

### ISSUE THREAD

**Issue by mdshearer** [enspiral/improvements#337]
With the contributor database upgrade completed, Ops are now working on reconciling our records to make sure all accounts are being paid for by some one or some org other than Foundation.

**Comment by charleydavenport** [comment]
Update: We've completed an audit of all Google Apps accounts and have sorted into those who are covered by an invoice and ventures. There are 15 GApps account-holders left currently not covered off by an invoice or a venture who have either been contacted or who are in queue to be removed. 

While this is nearly complete, it'll feel complete when these remaining accounts are either invoiced or removed.

**Comment by charleydavenport** [comment]
This is done - all accounts are up to date or are on track to be invoiced/removed.
