### ISSUE TITLE
Foundation Cobudget User List Clean-up

### ISSUE THREAD

**Issue by charleydavenport** [enspiral/improvements#340]
I've done an audit on the Fuondation Cobudget Accounts and found some that could be removed and a couple that required accounts. 

There are a couple of users who have 2 accounts, so need to check in with them about if they're using both. Also need to check on the purpose of a couple of the Admin accounts.

A consolidated spreadsheet has been created to track the recent user changes in case this affects Jessy-Kate's cobudget work. JK has been notified and this sheet has been shared directly in case. https://goo.gl/Aq9kyP

**Comment by joshuavial** [comment]
@charleydavenport was this ticket finished as part of the cobudget reboot or is it still outstanding?

**Comment by charleydavenport** [comment]
@joshuavial all done now... let's celebrate!
