### ISSUE TITLE
Contributor value exchange slide deck

### ISSUE THREAD

**Issue by whiskeyfix** [enspiral/improvements#343]
A clear slide deck for all contributors to understand and re-engage with the Enspiral Foundation.

Enspiral vision and mission
What we offer
What we ask
How to make the most of the engagement with Enspiral 

Important protocols and processes for your engagement.

**Comment by whiskeyfix** [comment]
https://docs.google.com/document/d/13yInXykoHirj3Ef7O_fLoFsniPG-iavEbb5wye6EmYk/edit

**Comment by coopchange** [comment]
this has been completed and turned into a webpage, welcome.enspiral.com, with an embedded slide deck... it does not include "How to make the most of the engagement with Enspiral" nor "Important protocols and processes for your engagement", but I suggest we turn those into other tickets

but before I move it to celebrate, @whiskeyfix do you have any concerns with that or other ways forward? Thanks.
