### ISSUE TITLE
Cobudget tax implications for 'core work'

### ISSUE THREAD

**Issue by whiskeyfix** [enspiral/improvements#349]
Foundation --> cobudget fund holding tax strategy

**Comment by whiskeyfix** [comment]
This ticket is to confirm and work out the formal tax / money handling processes for Enspiral Foundation to operate the Cobudget fund.

Questions to consider. 

* What are the correct legal accountability and compliance structures we need to consider for holding a bunch of money as a community fund and then distributing it out to people?
* Are we accountable for the actual contents of the buckets? 
* What are the legals about people 'paying themselves' to do work with these buckets?
* Where is the legal risk for this being held?
* How does the end of financial year situation work with cobudget rounds and EF holding money over that period? 

-----

@joshuavial @agentlewis when you did your tax recommendations I'm assuming you were looking at the relationship between contributors / ventures and foundation, rather than this Foundation to cobudget relationship. Is that correct?

**Comment by joshuavial** [comment]
@whiskeyfix actually I think the work we were doing as part of #319 covers cobudget tax liabilities as well - see the doc I shared on slack. Short version is I think we should treat cobudget funds as the Enspiral Foundation's money and we should have simple 'bucket contract' which anyone receiving money for a bucket agrees to which does things like absolve the foundation of legal liability and agree to not being an employee, charging GST if they are registered etc.

**Comment by coopchange** [comment]
I'm going to call this ticket done, and let someone raise another ticket for addressing the MVB's concerns about doing rounds as we used to, where 'discretionary' projects, or investing in Contributor's projects that may still be 'for the commons' but ostensibly lie outside of 'core work'... (see most recent MVB notes)

@whiskeyfix @susanbasterfield @KateBee1 tagging you in case you want to rescue any of the details in this ticket to put into a new one
