### ISSUE TITLE
Critical management Studies Course

### ISSUE THREAD

**Issue by simontegg** [enspiral/improvements#52]
Building on the existing work of the Book Club, I am coordinating a [Critical Management  Studies Course](https://www.loomio.org/d/sbMa6ngw/open-course-critical-management-studies) on loomio. 

What happens when we spend time exploring an issue deeply?
How will people respond to academic sources of knowledge?
Can we take learnings and apply them to practical improvements?

**Comment by bartdv** [comment]
Me too @simontegg @joshuavial

**Comment by joshuavial** [comment]
@simontegg is this still in progress?

**Comment by simontegg** [comment]
I'm no longer part of Enspiral so not on the loomio. You can close or archive this. 
The entire thrust of this project was to attempt demonstrate that praxes other than those espoused in the Refactor are valid and build a case for changing the agreements to reflect that.. 

That's way to tiresome. I've firmed my position to 'I will contribute and participate in Enspiral as a first-class citizen or not at all.'
