### ISSUE TITLE
Action first, discussion later if needed decision making

### ISSUE THREAD

**Issue by simontegg** [enspiral/improvements#56]
The handbook lacks a contributing guide. There is an [unresolved discussion](https://www.loomio.org/d/UyYZ2QEr/-refactor-enspiral-handbook) about the processes we could use to maintain and update the handbook.

Rather than facilitate that discussion and gain group agreement before taking action. I am updating the handbook with a [contributing guide](https://github.com/enspiral/handbook/blob/contributing/contributing.md) and notifying people afterwards. The latter is perhaps 'against the grain' of common practice in enspiral. I hope  to stimulate learning around "type 1" and "type 2" decision-making processes. #55

**Comment by joshuavial** [comment]
closed due to inactivity
