### ISSUE TITLE
Finalise venture stewards and introductions

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#59]
- [x] accounting
- [ ] services
- [x] EDA
- [x] Action Station
- [ ] Scoop
- [ ] BuckyBox
- [ ] Rabid

**Comment by susanbasterfield** [comment]
Wondering how hard to chase Bucky Box and Scoop?  Still in chats with Rabid about their status - met with Breccan today agreed to reconvene early July.  Should have EXP and Accounting within the next 24 hours.  Agreed to wait on Services

**Comment by susanbasterfield** [comment]
OK feel good!  All done except Services, Bucky Box, Rabid and Scoop

**Comment by joshuavial** [comment]
I've split out individual tickets for the laggards and am calling this ticket done
