### ISSUE TITLE
Final clean up of funded buckets

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#60]
Work through all the funded buckets and get updates, archive or refund

**Comment by susanbasterfield** [comment]
I think these have been completed and paid out:

http://beta.cobudget.co/#/buckets/256	Lunch with Michel Bauwens - Yes - now archived.
http://beta.cobudget.co/#/buckets/273	Remote Meeting Improvement -  No invoice/payment
http://beta.cobudget.co/#/buckets/283	
Enspiral Christmas Picnic Pizza Party - Yes - (just invoiced today) - I will archive this bucket as part of reconciling the payments.
http://beta.cobudget.co/#/buckets/352	Take Orientation Aotearoa to an international conference - No invoice/payment
http://beta.cobudget.co/#/buckets/319	Enspiral Facebook Group Setup - No invoice/payment
http://beta.cobudget.co/#/buckets/395	
Better spam proofing for Enspiral domains (configure SPF/DKIM) - No invoice/payment
http://beta.cobudget.co/#/buckets/402	Transparency: Put Historical Reports the Handbook - No invoice/payment
http://beta.cobudget.co/#/buckets/432	Help Ops Unclog the Backlog - Yes - now archived.
http://beta.cobudget.co/#/buckets/300	Bling out the on boarding comms - Yes - now archived.

These two should have their finds returned to the funding pool

http://beta.cobudget.co/#/buckets/269	Open Podcast - Funds transferred out of Collab Funding to Reserves in my.enspiral. Bucket in Cobudget is now Archived
http://beta.cobudget.co/#/buckets/277	Organising Without Bosses Handbook - Funds transferred out of Collab Funding to Reserves in my.enspiral. Bucket in Cobudget is now Archived

These two seem to have stalled and I would recommend returning to funding pool (please confirm they haven’t been paid out?)

http://beta.cobudget.co/#/buckets/265	POC21 Sponsorship - No invoice/payment
http://beta.cobudget.co/#/buckets/263	Enspiral Website Update - No invoice/payment

**Comment by susanbasterfield** [comment]
Have sent emails to Babs, Alanna and Phill urging them to invoice.  Malcolm has sent a note to Derek re POC21 and Website buckets saying the funds will be returned if he doesn't hear otherwise by 27th.

**Comment by susanbasterfield** [comment]
I am comfortable to close this ticket pending advice
