### ISSUE TITLE
change handbook contribution process to always have a pull request

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#73]
make every change through a pull request so it is visible and we follow an advice process

**Comment by joshuavial** [comment]
Any updates on this @simontegg - do you want me to pick it up?

**Comment by rdbartlett** [comment]
I'm happy to pair on this. Keen for this to include an update to the contributor guidelines which I feel is currently pretty impenetrable.

**Comment by rdbartlett** [comment]
I've proposed the change here: https://github.com/enspiral/handbook/pull/17

**Comment by rdbartlett** [comment]
Addressed by https://github.com/enspiral/handbook/pull/17 and tweaked by https://github.com/enspiral/handbook/pull/18
