### ISSUE TITLE
Enspiral self organising course

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#80]
What if we we extended the 6 weekly emails Chloe wrote for introducing new people to Enspiral into a six week course on self organising?

We've learned some good things in running phase 0 for Dev Academy about how to do cohort based remote education and if someone was keen to work on the content I would be happy to help structure education delivery part.

**Comment by agentlewis** [comment]
@alannallama ++ 
 I'd love to hear more about what Marianne has done that sounds like a great mvp that we can start towards now.

@whiskeyfix  love it - sounds big, very big. Perhaps this is more what aim to be the final project rather than going straight for it. thoughts?
