### ISSUE TITLE
report on total number of contributors over time

### ISSUE THREAD

**Issue by joshuavial** [enspiral/improvements#82]
It would be great to see a report of total number of contributors per month.

I just noticed that there are 276 people in Loomio and there were over 300 before so it looks like folks are dropping away and it would be good to track it so everyone is aware.

**Comment by susanbasterfield** [comment]
hi @simontegg any news on this?

**Comment by mdshearer** [comment]
@susanbasterfield I went ahead and created something a little less pretty than Simon can do, over [here](https://docs.google.com/spreadsheets/d/1-ZdYOEZ9KXpd8W166Pt-uTQdrsoXcmgZkURU3955L-w/edit#gid=554251020).

**Comment by susanbasterfield** [comment]
@mdshearer cool!  any chance of a total column?

**Comment by mdshearer** [comment]
@susanbasterfield Total of what? There's already a total on 3 of the tabs not sure what else to add.

**Comment by susanbasterfield** [comment]
@mdshearer actual active contributors - the changes are great but nice to see the actual number is helpful too.  I could to the net subtraction of course but need to know the starting point 💃

**Comment by charleydavenport** [comment]
@susanbasterfield (and anyone else interested)... here's a link to the [Contributor list](https://docs.google.com/spreadsheets/d/1-ZdYOEZ9KXpd8W166Pt-uTQdrsoXcmgZkURU3955L-w/edit#gid=206903456). It pulls information from a different more zap-sensitive database that holds the key workflow for all of the contributor.

**Comment by mdshearer** [comment]
ie. Different tab, same sheet. Just need to change to the Contributors tab, it has a total on it.

**Comment by susanbasterfield** [comment]
this is great, @charleydavenport took me on a tour :D  thanks @mdshearer

**Comment by mdshearer** [comment]
We've setup an MVP which is running well.
