### ISSUE TITLE
Andrew Little, Grant Robertson, Jacinda Adern Visit 3rd June

### ISSUE THREAD

**Issue by susanbasterfield** [enspiral/improvements#93]

**Comment by silviazuur** [comment]
@joshuavial are they coming to EDA? I was at the Labour caucus thing last week - happy to help if needed

**Comment by joshuavial** [comment]
@silviazuur yes, the plan is they come to EDA

**Comment by simontegg** [comment]
I know Jacinda personally and I love showing people round EDA. Can host.

**Comment by joshuavial** [comment]
@simontegg great - it's at 10 this friday but is only Andrew and Grant now

**Comment by susanbasterfield** [comment]
@joshua please check the #wellington slack only Grant now - what time???  Would be good to post on the #wellington channel as a few people (via slack) have expressed interest in being there

**Comment by joshuavial** [comment]
We are now down to just Grant

**Comment by joshuavial** [comment]
Grant visited, it was grand
