### ISSUE TITLE
Donate Button

### ISSUE THREAD

**Issue by samrye** [enspiral/improvements#94]
Basic hypothesis:
People love Enspiral, many can't contribute time or energy, but want to back Enspiral to increase Impact.

By launching a Donate button on the front page, we will generate $1000/month in donations, by investing in communications which links back to our homepage.

My suggestion is that it's accompanied by a blog post which outlines we will allocate the money through Cobudget internally.

I'd also love to see the same tactic tested with an external group which Enspiralites can pitch ideas to.

**Comment by joshuavial** [comment]
This keeps getting deprioritized, removing from sprint

**Comment by joshuavial** [comment]
Kate Beecroft is keen to pick this up I believe - will assign it to her when she is on github

**Comment by KateBee1** [comment]
I'm looking at using PayPal and generating a Donate button but the other option is Press Patron - https://www.presspatron.com/ who will modify the experience a little to suit us.  Keen to talk to someone else about which one makes most sense to use. Silvia is asking Deloitte some questions about receipts and gst etc and then we will be at a stage to put it up.

**Comment by joshuavial** [comment]
Discussion on this is progressing - https://www.loomio.org/d/YTBraI8x/should-we-use-open-collective-to-process-some-financial-contributions-

**Comment by phillcoxon** [comment]
Update: we've been exploring and testing a solution for one-off and subscription contributions for the Enspiral.com.  

I've sent a suggested cobudget funding request outline to @KateBee1 so that we can get a bucket up, funded and Enspiral.com receiving contribution revenue very quickly.

**Comment by kiwialexnz** [comment]
Hey @phillcoxon & @KateBee1, Alex here from @presspatron. Are you still keen to explore the option of using PressPatron for processing your one-time & monthly contributions?

**Comment by phillcoxon** [comment]
Hi @kiwialexnz.  We have a WordPress based solution using the GiveWP.com plugin which has been tested and looks perfect for a range of applications so we are putting in a funding application for that in the next cobudget round starting in a couple of days.

**Comment by alanna** [comment]
I still think OpenCollective is a better solution. Stripe has come out of beta in NZ now so it would be super easy to set up. Let me know if you want to talk more about it.

**Comment by phillcoxon** [comment]
@alannallama the GiveWP.com solution we are proposing will allow Enspiral to: 

- set up any number of concurrent SSL secured contribution and fundraising forms on the Enspiral.com website. 
- receive payments via Stripe & PayPal (among other payment gateways) as well as manually recording payments (if contributors paid via bank account, my.enspiral etc)
- select whether contribution forms are a standalone full page, modal pop up or inserted into existing page content
- accept general contributions and fund-raising for specific financial goals 
- have great flexibility in regard to contribution options - pre-determined contribution amounts (select from a set of choices), visitors choose their own amount etc.
- accept both one off and automated recurring subscription contributions. Subscription payments can be a finite set of future payments (say 12 months at $xx/month) or ongoing until canceled. 
- optionally allow contributors to manage their own subscription payments - cancel or make changes
- optionally add custom fields to each contribution forms to collect additional information
- optionally invite contributors to cover the payment gateway processing fees as part of their contribution
- optionally require contributors to accept terms & conditions (with terms & conditions able to be set separately for each contribution form)
- automatically remail PDF receipts for contributors
- optionally add contributors to a mailing list (most major mailing list providers supported, including MailChimp)
- access detailed reports on financial contributions & monthly subscription revenue (allowing Enspiral Foundation to forecast future contribution income). Reports can be set up to be automatically emailed to stakeholders. 
- use google analytics reporting for individual contribution form pages
- use Zapier.com integration opening up many tracking & processing opportunities for Ensprial. 
 For example, variable contribution funding that automatically splits funds to Foundation & Cobudget, tracking contribution amounts & contributor information to spreadsheets and integrating existing Operations Team processes. 

The GiveWP plugin is extremely well regarded with continuous development & responsive support. 

Here's a screenshot of one of the testing pages demonstrating various features: a specific funding target, pre-defined donation levels, ability for visitors to specify their own amount, option to make it an automated monthly subscription, option for donor to cover the credit card processing costs, and optional terms & conditions:

![](https://i.imgur.com/B6U281z.png)

Given the above do you still feel using OpenCollective would be a better solution?

**Comment by alanna** [comment]
Cool... if those features are the most important then GiveWP sounds good. 

Open Collective has different features, like automatic transparency of where money comes from and how it's spent, the ability to host multiple collectives under one 'host' (legal entity/bank account) with their own budgets, built-in events so ticket sales can go direct to the budget, different sponsorship tiers so you can highlight people backing the community at different levels, and as of very soon custom tiers so you can sell swag or offer other rewards at different contribution levels. It also offers many of the features you listed, but not all.

So... pro's and con's depending on what your focus is.

**Comment by whiskeyfix** [comment]
FYI: I've added this to the #balance-the-books workstream and will continue to support / check in on this ticket in context of that work. @KateBee1 @phillcoxon keen to understand what next steps with decisions to make and resourcing to find if there is anything else  standing in the way of us moving ahead here.

**Comment by phillcoxon** [comment]
Hey @whiskeyfix.  

The proposed solution is ready to go. It's been tested using a development version granted to us by GiveWP (not free - we still need to purchase our own copy) and is working great for both one off and subscription donations through a test stripe account.  

There are very minor tweaks required (replacing "donations" with "contributions" in the user interface) but we can have it up and receiving donations on the Enspiral.com website very quickly.  

A bucket funding proposal was sent to @KateBee1 to be included in the next CoBudget round to cover the software license and integration/testing.

So the only steps required to get basic donations up and running are: 

* Set up a Stripe account for Enspiral Foundation if one doesn't already exist
* Fund the cost of the software & dev setup time via Cobudget. 

After that we can work with Optmi to set up more complex contribution processes such as variable contributions with donations split between Foundation and Cobudget and automated via Zapier.

**Comment by KateBee1** [comment]
@whiskeyfix as @phillcoxon says we're going to experiment with the donate button for 1 year with the GiveWP - we've chosen this as it is fit for purpose for donate button and we want to achieve with that (i.e. see if people will actually donate). 

We're waiting for the Facilitated Cobudget Round to begin and then I will post the bucket. Once it's filled we'll install the plugin. At that point it will be necessary to have a discussion about the comms and marketing around the donate button and use of the money. 

Once small block on this is that Deloitte haven't confirmed our text for ensuring the tax legality - however, we've established

**Comment by joshuavial** [comment]
@phillcoxon I've been working on the monthly contributor workflow with optimi and @agentlewis and we were planning to have no credit cards, invoices only as a way of contributors paying their monthly subs - let's sync up for a call to see if we can align work streams.

**Comment by coopchange** [comment]
@agentlewis @phillcoxon is this ticket ready to be closed? thanks!

**Comment by danalexilewis** [comment]
@coopchange yes it is
