### ISSUE TITLE
Being strategic about the attention economy

### ISSUE THREAD

**Issue by alannallama** [enspiral/improvements#95]
Enspiral is an interconnected and interdependent network. That's what gives it its strength and promise. That interconnectedness functions on several layers at once, which you could thing of as 'economies', in terms of flows of resources that can create value: the financial economy, the reputation and trust economy, and the attention economy. I think we talk quite a lot about the first two - how to spend money wisely, the importance of protecting our brand - but not enough about the third one. It seems to me that people aren't very aware that our open, participatory way of organising is like giving everyone a debit card linked to our collective attention economy. Your freedom to access it is limitless, but the total resource itself is not.

But as knowledge workers, the attention could be considered our most precious resource. By decentralising our communications channels and decision-making, we invite everyone to access the network's attention, and to suggest it be directed at what they think is important. That's amazing - it's how we swarm on projects, collaborate, and learn. But do we have enough awareness of how precious our collective attention actually is? Do we stop and ask ourselves, if I had a limited amount of times to swipe that attention debit card, would I spend it on this thing I'm about to raise? Is now the time for this discussion? Do people see that's it's not just about what _they_ want to pay attention to, but that because of our interconnectedness, other's are listening, and spending their budget of total Enspiral attention points, too?

I don't have any desire to centrally control what is considered important, or what the network pays attention to. This is a large and diverse place, and different pockets will be interested in different things. There's room for all of it. I am, however, interested in what we can do to raise the level of self-awareness about engaging with the attention economy, making a habit of stopping to ask key questions like "is this the most important thing we could be working on right now?" and generally increasing the cultural skill and awareness of this precious resource. 

I have a feeling it's very "cheap" to garner attention, and sometimes that's not fully matched with how expensive it is to actually transform that attention into action, change, or tangible initiatives. Sometimes it's totally worth it to spend attention just talking something out and exploring, but often I think it's actually not. The costs of the attention economy are easy to externalise. Could we think about the attention economy in terms of the Full Circle modal? If something is never going to go beyond "inquire" or "envision", I sometimes question if it's a good use of attention economy resources. Then again, you never know what will turn into something amazing, and we absolutely need to freedom to communicate openly, throw ideas around, and experiment. 

How much of this is down to very practical issues with our comms channels, and how much of it is about deeper cultural issues? How does interacting with the attention economy intersect with our values around diversity and equality (some people are a lot more willing to call for collective attention than others)? 

Obviously I have a lot more questions than answers. I don't know how an abstract issue like this could be scoped into anything useful, but I'm putting it here because I think about it a lot and it comes up as a layer on a lot of interactions around Enspiral for me.

**Comment by simontegg** [comment]
Relevant article 
https://aeon.co/essays/does-each-click-of-attention-cost-a-bit-of-ourselves
