### ISSUE TITLE
Acting on Feedback from the Opt-in Form

### ISSUE THREAD

**Issue by alannallama** [enspiral/improvements#97]
As part of the contributor opt-in process, we collect feedback from people about their experience with Enspiral (whether they are opting to stay or go). We don't have a plan for acting on or using this information. I am pretty sure Ops is checking these responses and answering straightforward questions - but I don't think they are resourced to engage more deeply than that (maybe @mdshearer can confirm what they are doing now). I think that feedback from that channel should be occasionally reviewed, and improvements extracted to add here on the issues list.

**Comment by mdshearer** [comment]
I've setup a spreadsheet for Catalysts to view feedback. New feedback is zapped in automatically.
