### ISSUE TITLE
Quarterly Venture Reporting Process

### ISSUE THREAD

**Issue by alannallama** [enspiral/improvements#98]
We have decided that stewards will be responsible for ensuring venture reports are submitted. But what about the "meta" process - things like determining the timeline and deadlines, making sure reminder emails go out, collating the final results into a report, etc. Is this the Catalyst's job? Also, we never finalised the [venture reporting form](https://docs.google.com/forms/d/11Oz-HM1Wt8CbzxZpzGmjjFcd-sp9vahoqcLuL3UysT4/viewform) itself - will need another good think through before venture reporting kicks off.

**Comment by joshuavial** [comment]
closing this in favour of #111
